"use client";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, Check, Send } from "lucide-react";
import type { ActivityDetail as ActivityDto, SubmissionItemInput } from "@/specs/api.contracts";
import { apiMutation, useLiveApi } from "./live-api";
import { EmptyState, ErrorState, LoadingState } from "./state-lab";

export function ActivityDetail() {
  const search = useSearchParams();
  const assignmentId = search.get("assignmentId") ?? (process.env.NEXT_PUBLIC_DEMO_MODE === "true" ? "00000000-0000-4000-8000-000000000005" : null);
  const { data, error, loading, reload } = useLiveApi<ActivityDto>(assignmentId ? `/api/student/activities/${assignmentId}` : null);
  const [values, setValues] = useState<Record<string, string>>({}); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const draftItems = useMemo<SubmissionItemInput[]>(() => data?.requirements.flatMap((r) => { const value = values[r.id]?.trim(); if (!value) return []; return r.kind === "text" ? [{ requirementId:r.id, kind:r.kind, textValue:value }] : [{ requirementId:r.id, kind:r.kind, urlValue:value } as SubmissionItemInput]; }) ?? [], [data, values]);
  if (!assignmentId) return <EmptyState scope="atividade selecionada" />;
  if (loading) return <LoadingState />; if (error) return <ErrorState retry={reload} message={error.message} />; if (!data) return <EmptyState scope="atividade liberada" />;
  const activity = data;
  async function save(submit: boolean) { setSaving(true); setMessage(null); try { const draft = await apiMutation<{ id:string }>(`/api/student/activities/${activity.assignmentId}/draft`, "PUT", { items:draftItems }); if (submit) await apiMutation(`/api/student/activities/${activity.assignmentId}/submit`, "POST", { expectedDraftId:draft.id }); setMessage(submit ? "Versão enviada para revisão." : "Rascunho salvo."); await reload(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Não foi possível salvar."); } finally { setSaving(false); } }
  return <><Link href="/" className="back-link"><ArrowLeft />Voltar ao início</Link><header className="activity-header"><span className="meta-label">Aula {data.lessonPosition.toString().padStart(2,"0")}</span><h1>{data.title}</h1><p>{data.objective}</p><div className="activity-meta"><span>{data.estimatedMinutes} min</span><span>{data.dueAt ? `Prazo: ${new Date(data.dueAt).toLocaleString("pt-BR")}` : "Sem prazo"}</span><span className="version-marker">{data.status}</span></div></header><div className="activity-layout"><div className="activity-main"><section className="work-sheet"><h2>O que precisa acontecer</h2><p>{data.instructions}</p><p>{data.continuityGuidance}</p></section><section className="work-sheet submission-sheet"><div className="section-heading"><div><span className="meta-label">Envio de evidência</span><h2>Registre sua versão</h2></div></div>{data.requirements.map((requirement) => <label className="floating-field" key={requirement.id}><span>{requirement.label}{requirement.required ? " *" : ""}</span><input value={values[requirement.id] ?? ""} onChange={(event) => setValues((current) => ({...current,[requirement.id]:event.target.value}))} placeholder={requirement.kind === "text" ? "Descreva sua decisão" : "https://"} required={requirement.required} /><small>{requirement.kind === "github_repository" ? "Use o link HTTPS do GitHub." : requirement.kind === "external_link" ? "Use um link HTTPS." : "Escreva de forma objetiva."}</small></label>)}<div className="submit-actions"><button type="button" className="button-secondary" disabled={saving} onClick={() => void save(false)}>Salvar rascunho</button><button type="button" className="button-primary" disabled={saving} onClick={() => void save(true)}>Enviar versão <Send /></button></div>{message && <p className="save-status" role="status"><Check />{message}</p>}</section></div><aside className="activity-aside"><section><span className="meta-label">Critérios visíveis</span><h2>Antes de enviar</h2><ul className="criteria-list">{data.criteria.map((criterion) => <li key={criterion.id}><Check />{criterion.label}: {criterion.description}</li>)}</ul></section><section><span className="meta-label">Histórico</span><h2>Versões e feedback</h2>{data.submissionHistory.length ? data.submissionHistory.map((submission) => <div className="risk-row" key={submission.id}><span><strong>Versão {submission.version} · {submission.isDraft ? "rascunho" : "enviada"}</strong><small>{submission.review ? submission.review.feedback : "Aguardando revisão."}</small></span></div>) : <p>Nenhuma versão enviada ainda.</p>}</section></aside></div></>;
}
