begin;

create or replace function logos_academy.student_home(p_tenant_id uuid,p_actor_user_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare e uuid; r jsonb; a jsonb; s jsonb;
begin
 select en.id into e from logos_academy.enrollments en join logos_academy.student_profiles sp on sp.tenant_id=en.tenant_id and sp.id=en.student_profile_id where en.tenant_id=p_tenant_id and sp.user_id=p_actor_user_id and en.deleted_at is null and sp.deleted_at is null order by en.created_at desc limit 1;
 if e is null then raise exception using errcode='42501',message='student enrollment required'; end if;
 select jsonb_build_object('kind',case when aa.status='revision_requested' then 'revise_submission' else 'view_feedback' end,'assignmentId',aa.id,'label',case when aa.status='revision_requested' then 'Revisar entrega' else 'Ver feedback' end) into a from logos_academy.activity_assignments aa left join logos_academy.submissions su on su.tenant_id=aa.tenant_id and su.activity_assignment_id=aa.id and not su.is_draft and su.deleted_at is null left join logos_academy.reviews rv on rv.tenant_id=su.tenant_id and rv.submission_id=su.id and rv.deleted_at is null left join logos_academy.feedback_receipts fr on fr.tenant_id=rv.tenant_id and fr.review_id=rv.id and fr.deleted_at is null where aa.tenant_id=p_tenant_id and aa.enrollment_id=e and aa.deleted_at is null and (aa.status='revision_requested' or (rv.id is not null and fr.id is null)) order by case when aa.status='revision_requested' then 0 else 1 end,rv.reviewed_at desc nulls last limit 1;
 if a is null then select jsonb_build_object('kind','continue_activity','assignmentId',id,'label','Continuar atividade') into a from logos_academy.activity_assignments where tenant_id=p_tenant_id and enrollment_id=e and status in ('available','draft') and deleted_at is null order by due_at nulls last limit 1; end if;
 if a is null then a:=jsonb_build_object('kind','none','label','Nenhuma pendência agora.'); end if;
 select jsonb_build_object('id',s.id,'lessonPosition',(select count(*) from logos_academy.lesson_templates lt2 join logos_academy.cycles c2 on c2.tenant_id=lt2.tenant_id and c2.id=lt2.cycle_id join logos_academy.lesson_templates lt on lt.tenant_id=s.tenant_id and lt.id=s.lesson_template_id join logos_academy.cycles c on c.tenant_id=lt.tenant_id and c.id=lt.cycle_id where lt2.tenant_id=s.tenant_id and c2.curriculum_id=c.curriculum_id and (c2.position,lt2.position)<=(c.position,lt.position)),'lessonTitle',lt.title,'startsAt',s.starts_at,'endsAt',s.ends_at,'status',s.status) into s from logos_academy.sessions s join logos_academy.lesson_templates lt on lt.tenant_id=s.tenant_id and lt.id=s.lesson_template_id join logos_academy.enrollments en on en.tenant_id=s.tenant_id and en.id=e where s.tenant_id=p_tenant_id and s.deleted_at is null and s.starts_at>=now() and ((en.class_id is not null and s.class_id=en.class_id) or s.enrollment_id=en.id) order by s.starts_at limit 1;
 return jsonb_build_object('primaryAction',a,'nextSession',s,'recentFeedback',null,'currentProject',null,'pendingMakeupCount',0);
end; $$;

create or replace function logos_academy.student_journey(p_tenant_id uuid,p_actor_user_id uuid,p_enrollment_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare v jsonb;
begin
 if not exists(select 1 from logos_academy.enrollments e join logos_academy.student_profiles sp on sp.tenant_id=e.tenant_id and sp.id=e.student_profile_id where e.tenant_id=p_tenant_id and e.id=p_enrollment_id and sp.user_id=p_actor_user_id and e.deleted_at is null) then raise exception using errcode='42501',message='student enrollment required'; end if;
 select jsonb_build_object('enrollment',jsonb_build_object('id',e.id,'studentId',e.student_profile_id,'studentName',u.display_name,'curriculumName',cu.name,'kind',e.kind,'classId',e.class_id,'status',e.status,'activatedAt',e.activated_at,'completedAt',e.completed_at),'projects',coalesce((select jsonb_agg(jsonb_build_object('id',coalesce(pr.id,cy.id),'cyclePosition',cy.position,'title',cy.project_title,'status',coalesce(pr.status,'locked'),'approvedAt',pr.approved_at,'completedActivityCount',0,'activityCount',0) order by cy.position) from logos_academy.cycles cy left join logos_academy.project_records pr on pr.tenant_id=cy.tenant_id and pr.cycle_id=cy.id and pr.enrollment_id=e.id and pr.deleted_at is null where cy.tenant_id=e.tenant_id and cy.curriculum_id=e.curriculum_id and cy.deleted_at is null),'[]'::jsonb),'sessionsCompleted',(select count(*) from logos_academy.sessions s where s.tenant_id=e.tenant_id and s.status='completed' and s.deleted_at is null and ((e.class_id is not null and s.class_id=e.class_id) or s.enrollment_id=e.id)),'sessionsTotal',16) into v from logos_academy.enrollments e join logos_academy.student_profiles sp on sp.tenant_id=e.tenant_id and sp.id=e.student_profile_id join logos_academy.users u on u.tenant_id=sp.tenant_id and u.id=sp.user_id join logos_academy.curricula cu on cu.tenant_id=e.tenant_id and cu.id=e.curriculum_id where e.tenant_id=p_tenant_id and e.id=p_enrollment_id; return v;
end; $$;

create or replace function logos_academy.student_concepts_page(p_tenant_id uuid,p_actor_user_id uuid,p_search text default null,p_cursor text default null,p_limit integer default 25) returns jsonb language plpgsql security definer set search_path='' as $$
declare v jsonb;
begin
 if not exists(select 1 from logos_academy.student_profiles sp where sp.tenant_id=p_tenant_id and sp.user_id=p_actor_user_id and sp.deleted_at is null) then raise exception using errcode='42501',message='student required'; end if;
 select jsonb_build_object('items',coalesce(jsonb_agg(jsonb_build_object('id',c.id,'slug',c.slug,'title',c.title,'summary',c.summary,'releasedAt',now()) order by c.title),'[]'::jsonb),'nextCursor',null) into v from logos_academy.concepts c where c.tenant_id=p_tenant_id and c.deleted_at is null and exists(select 1 from logos_academy.lesson_concepts lc where lc.tenant_id=c.tenant_id and lc.concept_id=c.id and private.can_read_lesson(lc.tenant_id,lc.lesson_template_id)) and (coalesce(p_search,'')='' or lower(translate(c.title||' '||c.summary,'áàãâéêíóôõúç','aaaaeeiooouc')) like '%'||lower(translate(p_search,'áàãâéêíóôõúç','aaaaeeiooouc'))||'%') limit p_limit; return v;
end; $$;

create or replace function logos_academy.student_concept_detail(p_tenant_id uuid,p_actor_user_id uuid,p_concept_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare v jsonb; begin select jsonb_build_object('id',c.id,'slug',c.slug,'title',c.title,'summary',c.summary,'body',c.body,'releasedAt',now(),'relatedConcepts','[]'::jsonb) into v from logos_academy.concepts c where c.tenant_id=p_tenant_id and c.id=p_concept_id and c.deleted_at is null and exists(select 1 from logos_academy.lesson_concepts lc where lc.tenant_id=c.tenant_id and lc.concept_id=c.id and private.can_read_lesson(lc.tenant_id,lc.lesson_template_id)); if v is null then raise exception using errcode='42501',message='concept not released'; end if; return v; end; $$;

create or replace function logos_academy.mark_review_seen(p_tenant_id uuid,p_actor_user_id uuid,p_review_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare sp uuid; result jsonb; begin select p.id into sp from logos_academy.student_profiles p where p.tenant_id=p_tenant_id and p.user_id=p_actor_user_id and p.deleted_at is null; insert into logos_academy.feedback_receipts(tenant_id,review_id,student_profile_id,seen_at) select p_tenant_id,p_review_id,sp,now() where exists(select 1 from logos_academy.reviews r join logos_academy.submissions s on s.tenant_id=r.tenant_id and s.id=r.submission_id join logos_academy.activity_assignments aa on aa.tenant_id=s.tenant_id and aa.id=s.activity_assignment_id join logos_academy.enrollments e on e.tenant_id=aa.tenant_id and e.id=aa.enrollment_id where r.tenant_id=p_tenant_id and r.id=p_review_id and e.student_profile_id=sp) on conflict on constraint feedback_receipts_active_key do update set seen_at=feedback_receipts.seen_at returning jsonb_build_object('id',p_review_id,'seenAt',seen_at) into result; return coalesce(result,'{}'::jsonb); end; $$;

revoke all on function logos_academy.student_home(uuid,uuid),logos_academy.student_journey(uuid,uuid,uuid),logos_academy.student_concepts_page(uuid,uuid,text,text,integer),logos_academy.student_concept_detail(uuid,uuid,uuid),logos_academy.mark_review_seen(uuid,uuid,uuid) from public,anon,authenticated;
grant execute on function logos_academy.student_home(uuid,uuid),logos_academy.student_journey(uuid,uuid,uuid),logos_academy.student_concepts_page(uuid,uuid,text,text,integer),logos_academy.student_concept_detail(uuid,uuid,uuid),logos_academy.mark_review_seen(uuid,uuid,uuid) to service_role;
notify pgrst,'reload schema'; commit;
