begin;

create or replace function logos_academy.student_home(p_tenant_id uuid,p_actor_user_id uuid,p_encryption_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare e logos_academy.enrollments%rowtype; sp logos_academy.student_profiles%rowtype; action jsonb; next_session jsonb; review_id uuid; recent jsonb; project jsonb; makeups integer;
begin
  if length(coalesce(p_encryption_key,''))=0 then raise exception using errcode='22023',message='encryption key required'; end if;
  select en.* into e from logos_academy.enrollments en join logos_academy.student_profiles p on p.tenant_id=en.tenant_id and p.id=en.student_profile_id where en.tenant_id=p_tenant_id and p.user_id=p_actor_user_id and en.deleted_at is null and p.deleted_at is null order by en.created_at desc limit 1;
  if e.id is null then raise exception using errcode='42501',message='student enrollment required'; end if;
  select * into sp from logos_academy.student_profiles where tenant_id=p_tenant_id and id=e.student_profile_id and deleted_at is null;
  select r.id into review_id from logos_academy.reviews r join logos_academy.submissions s on s.tenant_id=r.tenant_id and s.id=r.submission_id and s.deleted_at is null join logos_academy.activity_assignments aa on aa.tenant_id=s.tenant_id and aa.id=s.activity_assignment_id and aa.deleted_at is null where r.tenant_id=p_tenant_id and aa.enrollment_id=e.id and r.deleted_at is null order by r.reviewed_at desc,r.id desc limit 1;
  if review_id is not null then recent:=private.student_review_detail(p_tenant_id,review_id,sp.id,p_encryption_key); end if;
  select jsonb_build_object('kind','revise_submission','assignmentId',aa.id,'label','Revisar entrega') into action from logos_academy.activity_assignments aa where aa.tenant_id=p_tenant_id and aa.enrollment_id=e.id and aa.status='revision_requested' and aa.deleted_at is null order by aa.due_at nulls last,aa.id limit 1;
  if action is null then select jsonb_build_object('kind','view_feedback','assignmentId',aa.id,'label','Ver feedback') into action from logos_academy.activity_assignments aa join logos_academy.submissions s on s.tenant_id=aa.tenant_id and s.activity_assignment_id=aa.id and not s.is_draft and s.deleted_at is null join logos_academy.reviews r on r.tenant_id=s.tenant_id and r.submission_id=s.id and r.deleted_at is null left join logos_academy.feedback_receipts fr on fr.tenant_id=r.tenant_id and fr.review_id=r.id and fr.student_profile_id=sp.id and fr.deleted_at is null where aa.tenant_id=p_tenant_id and aa.enrollment_id=e.id and aa.deleted_at is null and fr.id is null order by r.reviewed_at desc,r.id desc limit 1; end if;
  if action is null then select jsonb_build_object('kind','continue_activity','assignmentId',id,'label','Continuar atividade') into action from logos_academy.activity_assignments where tenant_id=p_tenant_id and enrollment_id=e.id and status in ('available','draft') and deleted_at is null order by due_at nulls last,id limit 1; end if;
  if action is null and nullif(btrim(sp.github_username),'') is null then action:=jsonb_build_object('kind','setup_github','label','Conecte seu GitHub para registrar suas construções'); end if;
  if action is null then action:=jsonb_build_object('kind','none','label','Nenhuma pendência agora.'); end if;
  select jsonb_build_object('id',s.id,'lessonPosition',(select count(*) from logos_academy.lesson_templates all_lt join logos_academy.cycles all_c on all_c.tenant_id=all_lt.tenant_id and all_c.id=all_lt.cycle_id where all_lt.tenant_id=lt.tenant_id and all_c.curriculum_id=c.curriculum_id and all_lt.deleted_at is null and all_c.deleted_at is null and (all_c.position,all_lt.position)<=(c.position,lt.position)),'lessonTitle',lt.title,'startsAt',s.starts_at,'endsAt',s.ends_at,'status',s.status) into next_session from logos_academy.sessions s join logos_academy.lesson_templates lt on lt.tenant_id=s.tenant_id and lt.id=s.lesson_template_id join logos_academy.cycles c on c.tenant_id=lt.tenant_id and c.id=lt.cycle_id where s.tenant_id=p_tenant_id and s.deleted_at is null and s.starts_at>=now() and ((e.class_id is not null and s.class_id=e.class_id) or s.enrollment_id=e.id) order by s.starts_at,s.id limit 1;
  select private.student_project_summary(p_tenant_id,e.id,cy.id) into project from logos_academy.cycles cy where cy.tenant_id=p_tenant_id and cy.curriculum_id=e.curriculum_id and cy.deleted_at is null and exists(select 1 from logos_academy.activity_assignments aa join logos_academy.activity_templates at on at.tenant_id=aa.tenant_id and at.id=aa.activity_template_id join logos_academy.lesson_templates lt on lt.tenant_id=at.tenant_id and lt.id=at.lesson_template_id where aa.tenant_id=cy.tenant_id and aa.enrollment_id=e.id and lt.cycle_id=cy.id and aa.status<>'locked' and aa.deleted_at is null) order by cy.position limit 1;
  select count(*) into makeups from logos_academy.attendance_records ar left join logos_academy.makeup_records mr on mr.tenant_id=ar.tenant_id and mr.attendance_record_id=ar.id and mr.deleted_at is null where ar.tenant_id=p_tenant_id and ar.enrollment_id=e.id and ar.status in ('absent','excused_absence') and ar.deleted_at is null and mr.id is null;
  return jsonb_build_object('primaryAction',action,'nextSession',next_session,'recentFeedback',recent,'currentProject',project,'pendingMakeupCount',makeups);
end; $$;

create or replace function logos_academy.student_concepts_page(p_tenant_id uuid,p_actor_user_id uuid,p_search text default null,p_cursor text default null,p_limit integer default 25) returns jsonb language plpgsql security definer set search_path='' as $$
declare cursor_value jsonb:=private.admissions_page(p_cursor,p_limit); items jsonb; next_cursor text;
begin
  if not exists(select 1 from logos_academy.student_profiles sp where sp.tenant_id=p_tenant_id and sp.user_id=p_actor_user_id and sp.deleted_at is null) then raise exception using errcode='42501',message='student required'; end if;
  with rows as (select c.id,c.slug,c.title,c.summary,c.created_at,min(aa.released_at) released_at from logos_academy.concepts c join logos_academy.lesson_concepts lc on lc.tenant_id=c.tenant_id and lc.concept_id=c.id and lc.deleted_at is null join logos_academy.activity_templates at on at.tenant_id=lc.tenant_id and at.lesson_template_id=lc.lesson_template_id and at.deleted_at is null join logos_academy.activity_assignments aa on aa.tenant_id=at.tenant_id and aa.activity_template_id=at.id and aa.deleted_at is null join logos_academy.enrollments e on e.tenant_id=aa.tenant_id and e.id=aa.enrollment_id and e.deleted_at is null join logos_academy.student_profiles sp on sp.tenant_id=e.tenant_id and sp.id=e.student_profile_id and sp.deleted_at is null where c.tenant_id=p_tenant_id and c.deleted_at is null and sp.user_id=p_actor_user_id and aa.status<>'locked' and aa.released_at is not null and (coalesce(btrim(p_search),'')='' or translate(lower(c.title||' '||c.summary),'áàãâéêíóôõúç','aaaaeeiooouc') like '%'||translate(lower(btrim(p_search)),'áàãâéêíóôõúç','aaaaeeiooouc')||'%') and (cursor_value is null or (c.title,c.created_at,c.id)>((cursor_value->>0),(cursor_value->>1)::timestamptz,(cursor_value->>2)::uuid)) group by c.id,c.slug,c.title,c.summary,c.created_at order by c.title,c.created_at,c.id limit p_limit+1), page as(select * from rows limit p_limit), tail as(select * from rows offset p_limit limit 1), page_tail as(select * from page offset greatest(p_limit-1,0) limit 1) select coalesce(jsonb_agg(jsonb_build_object('id',id,'slug',slug,'title',title,'summary',summary,'releasedAt',released_at) order by title,created_at,id),'[]'::jsonb),(select case when exists(select 1 from tail) then encode(convert_to(jsonb_build_array(title,created_at,id)::text,'utf8'),'base64') end from page_tail) into items,next_cursor from page;
  return jsonb_build_object('items',items,'nextCursor',next_cursor);
end; $$;

revoke all on function logos_academy.student_home(uuid,uuid,text),logos_academy.student_concepts_page(uuid,uuid,text,text,integer) from public,anon,authenticated;
grant execute on function logos_academy.student_home(uuid,uuid,text),logos_academy.student_concepts_page(uuid,uuid,text,text,integer) to service_role;
notify pgrst,'reload schema';
commit;
