begin;

create or replace function private.student_actor_assignment(p_tenant_id uuid,p_actor_user_id uuid,p_assignment_id uuid,p_mutable boolean default false) returns logos_academy.activity_assignments language plpgsql security definer set search_path='' as $$
declare v logos_academy.activity_assignments%rowtype;
begin select aa.* into v from logos_academy.activity_assignments aa join logos_academy.enrollments e on e.tenant_id=aa.tenant_id and e.id=aa.enrollment_id join logos_academy.student_profiles sp on sp.tenant_id=e.tenant_id and sp.id=e.student_profile_id where aa.tenant_id=p_tenant_id and aa.id=p_assignment_id and aa.deleted_at is null and e.deleted_at is null and sp.deleted_at is null and sp.user_id=p_actor_user_id; if v.id is null or v.status='locked' or (p_mutable and not exists(select 1 from logos_academy.enrollments e where e.tenant_id=v.tenant_id and e.id=v.enrollment_id and e.status='active' and e.deleted_at is null)) then raise exception using errcode='42501',message='assignment not available'; end if; return v; end; $$;

create or replace function logos_academy.student_activity_detail(p_tenant_id uuid,p_actor_user_id uuid,p_assignment_id uuid,p_encryption_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare aa logos_academy.activity_assignments%rowtype; v jsonb;
begin aa:=private.student_actor_assignment(p_tenant_id,p_actor_user_id,p_assignment_id,false); select jsonb_build_object('id',at.id,'assignmentId',aa.id,'lessonPosition',lt.position,'title',at.title,'objective',at.objective,'instructions',at.instructions,'continuityGuidance',at.continuity_guidance,'estimatedMinutes',at.estimated_minutes,'dueAt',aa.due_at,'status',aa.status,'isOverdue',aa.due_at<now(),'supplementalInstructions',aa.supplemental_instructions,'concepts',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'slug',c.slug,'title',c.title,'summary',c.summary,'releasedAt',aa.released_at)) from logos_academy.lesson_concepts lc join logos_academy.concepts c on c.tenant_id=lc.tenant_id and c.id=lc.concept_id where lc.tenant_id=aa.tenant_id and lc.lesson_template_id=lt.id and lc.deleted_at is null and c.deleted_at is null),'[]'::jsonb),'requirements',coalesce((select jsonb_agg(jsonb_build_object('id',ar.id,'kind',ar.kind,'label',ar.label,'required',ar.is_required,'position',ar.position) order by ar.position) from logos_academy.activity_requirements ar where ar.tenant_id=aa.tenant_id and ar.activity_template_id=at.id and ar.deleted_at is null),'[]'::jsonb),'criteria',coalesce((select jsonb_agg(jsonb_build_object('id',ac.id,'label',ac.label,'description',ac.description,'position',ac.position) order by ac.position) from logos_academy.activity_criteria ac where ac.tenant_id=aa.tenant_id and ac.activity_template_id=at.id and ac.deleted_at is null),'[]'::jsonb)) into v from logos_academy.activity_templates at join logos_academy.lesson_templates lt on lt.tenant_id=at.tenant_id and lt.id=at.lesson_template_id where at.tenant_id=aa.tenant_id and at.id=aa.activity_template_id; return v; end; $$;

create or replace function logos_academy.student_save_draft(p_tenant_id uuid,p_actor_user_id uuid,p_assignment_id uuid,p_items jsonb,p_encryption_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare aa logos_academy.activity_assignments%rowtype; sp uuid; draft_id uuid; item jsonb;
begin if jsonb_typeof(p_items)<>'array' then raise exception using errcode='22023',message='items must be array'; end if; aa:=private.student_actor_assignment(p_tenant_id,p_actor_user_id,p_assignment_id,true); select id into sp from logos_academy.student_profiles where tenant_id=p_tenant_id and user_id=p_actor_user_id and deleted_at is null; insert into logos_academy.submissions(tenant_id,activity_assignment_id,version,is_draft) select p_tenant_id,aa.id,coalesce(max(version),0)+1,true from logos_academy.submissions where tenant_id=p_tenant_id and activity_assignment_id=aa.id on conflict do nothing returning id into draft_id; if draft_id is null then select id into draft_id from logos_academy.submissions where tenant_id=p_tenant_id and activity_assignment_id=aa.id and is_draft and deleted_at is null; end if; delete from logos_academy.submission_items where tenant_id=p_tenant_id and submission_id=draft_id; for item in select value from jsonb_array_elements(p_items) loop if not exists(select 1 from logos_academy.activity_requirements ar where ar.tenant_id=p_tenant_id and ar.id=(item->>'requirementId')::uuid and ar.activity_template_id=aa.activity_template_id and ar.deleted_at is null) then raise exception using errcode='22023',message='invalid requirement'; end if; if item->>'kind' in ('external_link','github_repository') and (item->>'urlValue') !~ '^https://' then raise exception using errcode='22023',message='HTTPS URL required'; end if; insert into logos_academy.submission_items(tenant_id,submission_id,activity_requirement_id,kind,text_value_encrypted,url_value_encrypted,uploaded_file_id) values(p_tenant_id,draft_id,(item->>'requirementId')::uuid,item->>'kind',case when item->>'kind'='text' then extensions.pgp_sym_encrypt(item->>'textValue',p_encryption_key) end,case when item->>'kind' in ('external_link','github_repository') then extensions.pgp_sym_encrypt(item->>'urlValue',p_encryption_key) end,case when item->>'kind'='file' then (item->>'fileId')::uuid end); end loop; update logos_academy.activity_assignments set status='draft' where id=aa.id and status='available'; return jsonb_build_object('id',draft_id,'assignmentId',aa.id,'isDraft',true,'submittedAt',null); end; $$;

create or replace function logos_academy.student_submit_activity(p_tenant_id uuid,p_actor_user_id uuid,p_assignment_id uuid,p_expected_draft_id uuid,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare aa logos_academy.activity_assignments%rowtype; draft logos_academy.submissions%rowtype;
begin aa:=private.student_actor_assignment(p_tenant_id,p_actor_user_id,p_assignment_id,true); select * into draft from logos_academy.submissions where tenant_id=p_tenant_id and id=p_expected_draft_id and activity_assignment_id=aa.id and is_draft and deleted_at is null for update; if draft.id is null then raise exception using errcode='40001',message='draft stale'; end if; if exists(select 1 from logos_academy.activity_requirements ar where ar.tenant_id=p_tenant_id and ar.activity_template_id=aa.activity_template_id and ar.is_required and ar.deleted_at is null and not exists(select 1 from logos_academy.submission_items si where si.tenant_id=p_tenant_id and si.submission_id=draft.id and si.activity_requirement_id=ar.id and si.deleted_at is null)) then raise exception using errcode='23514',message='required items missing'; end if; update logos_academy.submissions set is_draft=false,submitted_at=now() where id=draft.id; update logos_academy.activity_assignments set status='submitted' where id=aa.id; return jsonb_build_object('id',draft.id,'assignmentId',aa.id,'version',draft.version,'isDraft',false,'submittedAt',now()); end; $$;

revoke all on function private.student_actor_assignment(uuid,uuid,uuid,boolean),logos_academy.student_activity_detail(uuid,uuid,uuid,text),logos_academy.student_save_draft(uuid,uuid,uuid,jsonb,text),logos_academy.student_submit_activity(uuid,uuid,uuid,uuid,uuid) from public,anon,authenticated;
grant execute on function logos_academy.student_activity_detail(uuid,uuid,uuid,text),logos_academy.student_save_draft(uuid,uuid,uuid,jsonb,text),logos_academy.student_submit_activity(uuid,uuid,uuid,uuid,uuid) to service_role;
notify pgrst,'reload schema'; commit;
