begin;

create or replace function logos_academy.student_create_upload(p_tenant_id uuid,p_actor_user_id uuid,p_assignment_id uuid,p_filename text,p_content_type text,p_size_bytes integer,p_encryption_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare aa logos_academy.activity_assignments%rowtype; sp uuid; file_id uuid:=gen_random_uuid(); path text;
begin aa:=private.student_actor_assignment(p_tenant_id,p_actor_user_id,p_assignment_id,true); if p_size_bytes not between 1 and 20971520 or p_content_type not in ('application/pdf','text/plain','text/markdown','image/png','image/jpeg','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation') then raise exception using errcode='22023',message='invalid file metadata'; end if; select id into sp from logos_academy.student_profiles where tenant_id=p_tenant_id and user_id=p_actor_user_id and deleted_at is null; path:=p_tenant_id::text||'/'||sp::text||'/'||aa.id::text||'/'||file_id::text; insert into logos_academy.uploaded_files(id,tenant_id,student_profile_id,activity_assignment_id,uploaded_by_user_id,storage_path,filename_encrypted,content_type,size_bytes,status) values(file_id,p_tenant_id,sp,aa.id,p_actor_user_id,path,extensions.pgp_sym_encrypt(p_filename,p_encryption_key),p_content_type,p_size_bytes,'pending'); return jsonb_build_object('id',file_id,'assignmentId',aa.id,'contentType',p_content_type,'sizeBytes',p_size_bytes,'status','pending','storagePath',path); end; $$;

create or replace function logos_academy.student_finalize_upload(p_tenant_id uuid,p_actor_user_id uuid,p_file_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare f logos_academy.uploaded_files%rowtype; m jsonb;
begin select uf.* into f from logos_academy.uploaded_files uf join logos_academy.student_profiles sp on sp.tenant_id=uf.tenant_id and sp.id=uf.student_profile_id where uf.tenant_id=p_tenant_id and uf.id=p_file_id and uf.deleted_at is null and sp.user_id=p_actor_user_id for update; if f.id is null then raise exception using errcode='42501',message='file not available'; end if; perform private.student_actor_assignment(p_tenant_id,p_actor_user_id,f.activity_assignment_id,true); select metadata into m from storage.objects where bucket_id='submissions' and name=f.storage_path; if m is null or coalesce(m->>'size','') !~ '^[0-9]+$' or (m->>'size')::integer<>f.size_bytes or m->>'mimetype' is distinct from f.content_type then raise exception using errcode='23514',message='uploaded object mismatch'; end if; update logos_academy.uploaded_files set status='ready' where id=f.id; return jsonb_build_object('id',f.id,'assignmentId',f.activity_assignment_id,'contentType',f.content_type,'sizeBytes',f.size_bytes,'status','ready','storagePath',f.storage_path); end; $$;

create or replace function logos_academy.student_file_metadata(p_tenant_id uuid,p_actor_user_id uuid,p_file_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare f logos_academy.uploaded_files%rowtype;
begin select uf.* into f from logos_academy.uploaded_files uf join logos_academy.student_profiles sp on sp.tenant_id=uf.tenant_id and sp.id=uf.student_profile_id where uf.tenant_id=p_tenant_id and uf.id=p_file_id and uf.deleted_at is null and sp.user_id=p_actor_user_id; if f.id is null or f.status<>'ready' then raise exception using errcode='42501',message='file not available'; end if; return jsonb_build_object('id',f.id,'storagePath',f.storage_path); end; $$;
revoke all on function logos_academy.student_create_upload(uuid,uuid,uuid,text,text,integer,text),logos_academy.student_finalize_upload(uuid,uuid,uuid),logos_academy.student_file_metadata(uuid,uuid,uuid) from public,anon,authenticated;
grant execute on function logos_academy.student_create_upload(uuid,uuid,uuid,text,text,integer,text),logos_academy.student_finalize_upload(uuid,uuid,uuid),logos_academy.student_file_metadata(uuid,uuid,uuid) to service_role;
notify pgrst,'reload schema'; commit;
