begin;

create or replace function logos_academy.admin_reviews_page(p_tenant_id uuid,p_actor_user_id uuid,p_encryption_key text,p_class_id uuid default null,p_overdue_only boolean default false,p_cursor text default null,p_limit integer default 25) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_cursor jsonb:=private.admissions_page(p_cursor,p_limit); v_items jsonb; v_next text;
begin
  perform private.assert_tenant_admin(p_tenant_id,p_actor_user_id);
  if length(coalesce(p_encryption_key,''))=0 then raise exception using errcode='22023',message='encryption key required'; end if;
  with rows as (select s.id,s.submitted_at from logos_academy.submissions s join logos_academy.activity_assignments aa on aa.tenant_id=s.tenant_id and aa.id=s.activity_assignment_id and aa.deleted_at is null join logos_academy.enrollments e on e.tenant_id=aa.tenant_id and e.id=aa.enrollment_id and e.deleted_at is null where s.tenant_id=p_tenant_id and s.deleted_at is null and not s.is_draft and aa.status='submitted' and (p_class_id is null or e.class_id=p_class_id) and (not p_overdue_only or s.submitted_at<=now()-interval '48 hours') and (v_cursor is null or (s.submitted_at,s.id)>((v_cursor->>0)::timestamptz,(v_cursor->>1)::uuid)) order by s.submitted_at,s.id limit p_limit+1),page as(select * from rows limit p_limit),tail as(select * from rows offset p_limit limit 1),page_tail as(select * from page offset greatest(p_limit-1,0) limit 1)
  select coalesce(jsonb_agg(private.admin_submission_detail(p_tenant_id,id,p_encryption_key) order by submitted_at,id),'[]'::jsonb),(select case when exists(select 1 from tail) then encode(convert_to(jsonb_build_array(submitted_at,id)::text,'utf8'),'base64') end from page_tail) into v_items,v_next from page;
  return jsonb_build_object('items',v_items,'nextCursor',v_next);
end;
$$;

create or replace function private.project_summary_json(p_tenant_id uuid,p_enrollment_id uuid,p_cycle_id uuid) returns jsonb language sql stable security definer set search_path='' as $$
 select jsonb_build_object('id',pr.id,'cyclePosition',c.position,'title',c.project_title,'status',case when pr.status='locked' and exists(select 1 from logos_academy.activity_assignments aa join logos_academy.activity_templates at on at.tenant_id=aa.tenant_id and at.id=aa.activity_template_id join logos_academy.lesson_templates lt on lt.tenant_id=at.tenant_id and lt.id=at.lesson_template_id where aa.tenant_id=pr.tenant_id and aa.enrollment_id=pr.enrollment_id and lt.cycle_id=pr.cycle_id and aa.status<>'locked' and aa.deleted_at is null) then 'in_progress' else pr.status end,'approvedAt',pr.approved_at,'completedActivityCount',(select count(*) from logos_academy.activity_assignments aa join logos_academy.activity_templates at on at.tenant_id=aa.tenant_id and at.id=aa.activity_template_id join logos_academy.lesson_templates lt on lt.tenant_id=at.tenant_id and lt.id=at.lesson_template_id where aa.tenant_id=pr.tenant_id and aa.enrollment_id=pr.enrollment_id and lt.cycle_id=pr.cycle_id and aa.status='approved' and aa.deleted_at is null),'activityCount',(select count(*) from logos_academy.activity_assignments aa join logos_academy.activity_templates at on at.tenant_id=aa.tenant_id and at.id=aa.activity_template_id join logos_academy.lesson_templates lt on lt.tenant_id=at.tenant_id and lt.id=at.lesson_template_id where aa.tenant_id=pr.tenant_id and aa.enrollment_id=pr.enrollment_id and lt.cycle_id=pr.cycle_id and aa.deleted_at is null)) from logos_academy.project_records pr join logos_academy.cycles c on c.tenant_id=pr.tenant_id and c.id=pr.cycle_id where pr.tenant_id=p_tenant_id and pr.enrollment_id=p_enrollment_id and pr.cycle_id=p_cycle_id and pr.deleted_at is null;
$$;

create or replace function logos_academy.admin_record_presentation(p_tenant_id uuid,p_actor_user_id uuid,p_enrollment_id uuid,p_kind text,p_performed_at timestamptz,p_contextual_note text,p_encryption_key text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
begin
  perform private.assert_tenant_admin(p_tenant_id,p_actor_user_id);
  if not exists(select 1 from logos_academy.enrollments e where e.tenant_id=p_tenant_id and e.id=p_enrollment_id and e.deleted_at is null) then raise exception using errcode='P0002',message='enrollment not found'; end if;
  return logos_academy.record_presentation(p_actor_user_id,p_enrollment_id,p_kind,p_performed_at,p_contextual_note,p_encryption_key,p_request_id)||jsonb_build_object('contextualNote',nullif(btrim(p_contextual_note),''));
end;
$$;

create or replace function logos_academy.admin_dashboard(p_tenant_id uuid,p_actor_user_id uuid,p_encryption_key text,p_class_id uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare v jsonb;
begin
 perform private.assert_tenant_admin(p_tenant_id,p_actor_user_id); if length(coalesce(p_encryption_key,''))=0 then raise exception using errcode='22023',message='encryption key required'; end if;
 if p_class_id is not null and not exists(select 1 from logos_academy.classes c where c.tenant_id=p_tenant_id and c.id=p_class_id and c.deleted_at is null) then raise exception using errcode='42501',message='class unavailable'; end if;
 with scope as (select e.id,e.student_profile_id,e.status from logos_academy.enrollments e where e.tenant_id=p_tenant_id and e.deleted_at is null and (p_class_id is null or e.class_id=p_class_id)), pending as (select aa.enrollment_id,count(*) filter(where aa.due_at<now() and aa.status in ('available','draft','revision_requested'))::int n from logos_academy.activity_assignments aa join scope s on s.id=aa.enrollment_id where aa.tenant_id=p_tenant_id and aa.deleted_at is null group by aa.enrollment_id), makeups as (select ar.enrollment_id,count(*)::int n from logos_academy.attendance_records ar join scope s on s.id=ar.enrollment_id where ar.tenant_id=p_tenant_id and ar.status='absent' and ar.deleted_at is null and not exists(select 1 from logos_academy.makeup_records mr where mr.tenant_id=ar.tenant_id and mr.attendance_record_id=ar.id and mr.deleted_at is null and mr.completed_at<=now()) group by ar.enrollment_id), rates as (select count(*) filter(where r.decision='approved')::numeric approved,count(*)::numeric total from logos_academy.reviews r join logos_academy.submissions su on su.tenant_id=r.tenant_id and su.id=r.submission_id join logos_academy.activity_assignments aa on aa.tenant_id=su.tenant_id and aa.id=su.activity_assignment_id join scope s on s.id=aa.enrollment_id where r.tenant_id=p_tenant_id and r.deleted_at is null and su.deleted_at is null)
 select jsonb_build_object('awaitingReviewCount',(select count(*) from logos_academy.activity_assignments aa join scope s on s.id=aa.enrollment_id where aa.tenant_id=p_tenant_id and aa.status='submitted' and aa.deleted_at is null),'feedbackDueSoonCount',(select count(*) from logos_academy.submissions su join logos_academy.activity_assignments aa on aa.tenant_id=su.tenant_id and aa.id=su.activity_assignment_id join scope s on s.id=aa.enrollment_id where su.tenant_id=p_tenant_id and not su.is_draft and aa.status='submitted' and su.submitted_at<=now()-interval '46 hours' and su.deleted_at is null),'overdueAssignmentCount',coalesce((select sum(n) from pending),0),'pendingMakeupCount',coalesce((select sum(n) from makeups),0),'deliveryApprovalRate',case when rates.total=0 then 0 else round(rates.approved/rates.total*100,2) end,'upcomingSessions',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'lessonPosition',lt.position,'lessonTitle',lt.title,'startsAt',s.starts_at,'endsAt',s.ends_at,'status',s.status) order by s.starts_at) from (select * from logos_academy.sessions s where s.tenant_id=p_tenant_id and s.deleted_at is null and s.status='scheduled' and s.starts_at>=now() and (p_class_id is null or s.class_id=p_class_id) order by s.starts_at limit 5) s join logos_academy.lesson_templates lt on lt.tenant_id=s.tenant_id and lt.id=s.lesson_template_id),'[]'::jsonb),'studentsAtRisk',coalesce((select jsonb_agg(jsonb_build_object('id',sp.id,'displayName',u.display_name,'email',extensions.pgp_sym_decrypt(u.email_encrypted,p_encryption_key),'githubUsername',sp.github_username,'activeEnrollmentCount',case when s.status='active' then 1 else 0 end,'pendingAssignmentCount',coalesce(p.n,0),'pendingMakeupCount',coalesce(m.n,0)) order by u.display_name) from scope s join logos_academy.student_profiles sp on sp.tenant_id=p_tenant_id and sp.id=s.student_profile_id join logos_academy.users u on u.tenant_id=sp.tenant_id and u.id=sp.user_id left join pending p on p.enrollment_id=s.id left join makeups m on m.enrollment_id=s.id where coalesce(p.n,0)>0 or coalesce(m.n,0)>0),'[]'::jsonb)) into v from rates;
 return v;
end;
$$;

revoke all on function logos_academy.admin_reviews_page(uuid,uuid,text,uuid,boolean,text,integer),private.project_summary_json(uuid,uuid,uuid),logos_academy.admin_record_presentation(uuid,uuid,uuid,text,timestamptz,text,text,uuid),logos_academy.admin_dashboard(uuid,uuid,text,uuid) from public,anon,authenticated;
grant execute on function logos_academy.admin_reviews_page(uuid,uuid,text,uuid,boolean,text,integer),logos_academy.admin_record_presentation(uuid,uuid,uuid,text,timestamptz,text,text,uuid),logos_academy.admin_dashboard(uuid,uuid,text,uuid) to service_role;
notify pgrst,'reload schema'; commit;
