begin;

-- Explorer v2 is a new immutable namespace. Explorer v1 rows and their dependents
-- remain untouched so historical enrollments, assignments and submissions keep working.
with operational_tenant as (
  select id from logos_academy.tenants where slug = 'logos-academy' and deleted_at is null
)
insert into logos_academy.curricula (id,tenant_id,name,version,status)
select md5('logos-academy-explorer-v2-curriculum')::uuid,id,'Explorer','v2','active'
from operational_tenant
on conflict do nothing;

with operational_tenant as (
  select id from logos_academy.tenants where slug = 'logos-academy' and deleted_at is null
), cycle_data(position,title,challenge,problem,audience,expected_result,quality_criteria,concepts) as (
  values
    (1::smallint,'Meu Assistente Inteligente','Criar um assistente de IA útil, confiável e fácil de explicar para um público específico.','Pedidos genéricos produzem respostas genéricas e pouco confiáveis.','Uma pessoa que precisa resolver uma tarefa recorrente com apoio de IA.','Assistente com objetivo, personalidade, prompt principal, exemplos, testes e documentação.',array['Objetivo e público claros','Prompt estruturado','Respostas testadas e verificadas','Melhoria registrada após os testes'],array['Prompt','Contexto','Restrições','Testes','Verificação']),
    (2::smallint,'Creative Studio','Criar uma campanha visual que conduza uma decisão clara usando hierarquia, contraste e narrativa.','Mensagens visuais perdem força quando imagem, texto e chamada disputam a atenção.','Pessoas que precisam compreender a mensagem principal e saber o que fazer em poucos segundos.','Campanha autoral com conceito, imagem principal, vídeo curto, copy e processo documentado.',array['Uma mensagem principal perceptível','Hierarquia visual intencional','Imagem, texto e ação coerentes','Decisões explicadas entre versões'],array['Hierarquia visual','Contraste','Storytelling','Curadoria','Copy curta']),
    (3::smallint,'Automation Lab','Construir uma automação que transforme uma entrada real em um resultado verificável.','Tarefas repetitivas consomem tempo quando não existe um fluxo claro entre entrada, decisão e saída.','Um usuário que executa manualmente um processo simples e repetitivo.','Workflow com problema, usuário, diagrama, prompt, teste, resultado e documentação.',array['Fluxo com começo, meio e fim','Entrada e saída verificáveis','Condição de decisão explícita','Teste e resultado documentados'],array['Gatilho','Entrada','Processamento','Condição','Saída']),
    (4::smallint,'AI Product','Transformar um problema real em um produto de IA pequeno, demonstrável e bem documentado.','Boas ideias não viram produto sem problema, usuário, escopo e evidência de funcionamento.','Um usuário real afetado pelo problema escolhido pelo aluno.','MVP com problema, usuário, solução, fluxo, demonstração, documentação e apresentação.',array['Problema e usuário reais','Escopo de MVP demonstrável','Solução testada','Aprendizados e próximos passos explicados'],array['Problema','Usuário','Escopo','MVP','Demonstração'])
)
insert into logos_academy.cycles (
  id,tenant_id,curriculum_id,position,title,project_title,project_challenge,
  project_problem,project_audience,project_expected_result,project_quality_criteria,project_concepts
)
select md5('logos-academy-explorer-v2-cycle-'||d.position)::uuid,t.id,
  md5('logos-academy-explorer-v2-curriculum')::uuid,d.position,d.title,d.title,d.challenge,
  d.problem,d.audience,d.expected_result,d.quality_criteria,d.concepts
from operational_tenant t cross join cycle_data d
on conflict do nothing;

create temporary table explorer_v2_activities(payload jsonb) on commit drop;
insert into explorer_v2_activities(payload) values ($json$
[
 {"position":1,"title":"Primeiro experimento com IA","challenge":"Descobrir em quatro testes quando uma resposta de IA ajuda, surpreende, parece estranha ou precisa ser verificada.","context":"IA generativa recebe uma entrada, processa padrões aprendidos e produz uma saída provável. Como ela pode errar, o primeiro hábito do Explorer deve ser observar e conferir, não aceitar automaticamente.","objective":"Explicar entrada e saída de uma IA generativa e reconhecer pelo menos uma resposta que exige verificação.","steps":["Perguntar algo cuja resposta o aluno já conhece.","Perguntar algo cuja resposta o aluno ainda não conhece.","Pedir a explicação simples de um tema.","Pedir uma resposta criativa.","Classificar e justificar cada resposta como boa, estranha, a verificar ou surpreendente."],"continuity":"Escolher um tema e um problema específico para o assistente do Ciclo 1; esse tema será usado na comparação da Atividade 2.","evidence":"Card ‘Primeiro experimento com IA generativa’, com síntese dos quatro testes e, se houver, print anonimizado.","planB":"Usar respostas previamente salvas, simular previsões de palavras no quadro e registrar as perguntas em papel para testar depois.","reflection":"Qual resposta mais exigiu sua verificação e por quê?","tools":"ChatGPT, Gemini ou respostas previamente salvas.","requirements":[["text",true,"Registro dos quatro testes: pergunta, resumo da resposta e classificação de cada teste."],["text",true,"Explicação crítica: por que a IA pode errar e qual resposta precisaria ser conferida."],["file",false,"Evidência visual: um print legível das interações, sem dados pessoais."]],"criteria":["Identifica a entrada enviada à IA.","Identifica a saída devolvida pela IA.","Registra exatamente quatro testes.","Aponta pelo menos uma resposta que exige verificação.","Explica em uma frase por que a IA pode errar."]},
 {"position":2,"title":"Duelo de ferramentas","challenge":"Executar a mesma tarefa em duas ferramentas e escolher a mais adequada com base em critérios observáveis.","context":"Ferramentas diferentes organizam contexto, fontes e respostas de modos distintos. A escolha deve depender da tarefa, não da aparência ou preferência pessoal.","objective":"Comparar duas ferramentas de IA pela mesma tarefa e justificar qual delas serve melhor ao assistente do ciclo.","steps":["Escolher uma tarefa ligada ao tema do assistente.","Executar exatamente a mesma tarefa em duas ferramentas.","Comparar clareza, utilidade, organização e necessidade de verificação.","Registrar diferenças observáveis.","Escolher uma ferramenta e justificar a decisão."],"continuity":"Levar a ferramenta escolhida e a tarefa de teste para a Atividade 3, onde o prompt será refinado em versões.","evidence":"Registro ‘Como escolhi a ferramenta do meu assistente’, contendo a tabela e a decisão.","planB":"Comparar duas respostas salvas, duas respostas da mesma ferramenta ou exemplos impressos preparados pelo professor.","reflection":"Que critério observável mais pesou na sua escolha?","tools":"Duas ferramentas de IA ou dois conjuntos de respostas salvas.","requirements":[["text",true,"Tabela comparativa: tarefa, ferramentas e comparação pelos quatro critérios."],["text",true,"Escolha justificada: ‘Eu escolheria X para Y porque Z’."],["file",false,"Comparação visual: print lado a lado, sem dados pessoais."]],"criteria":["Usa exatamente a mesma tarefa nas duas ferramentas.","Compara a clareza das respostas.","Compara a utilidade para a tarefa escolhida.","Considera a necessidade de verificar a resposta.","Justifica a escolha com pelo menos um critério observável."]},
 {"position":3,"title":"Laboratório de prompts: da v0 à v3","challenge":"Transformar uma instrução vaga em um prompt que contenha contexto, objetivo, restrições e formato de saída.","context":"Respostas úteis dependem de instruções compreensíveis. Iterar o mesmo prompt torna visível o efeito de cada decisão, sem incentivar a cópia de fórmulas prontas.","objective":"Produzir e comparar quatro estados do mesmo prompt: original, v1, v2 e v3.","steps":["Escrever a instrução original sem corrigir.","Adicionar contexto e objetivo na v1.","Adicionar restrições na v2.","Definir o formato de saída na v3.","Executar ou simular as quatro versões.","Comparar os resultados e registrar a mudança de maior efeito."],"continuity":"Adaptar a v3 para o prompt principal do assistente, acrescentando papel, público, personalidade e limite de atuação antes do Project Day.","evidence":"Peça ‘Antes e depois de um prompt’, com versões e aprendizado principal.","planB":"Revisar prompts impressos em grupo, simular respostas com colegas e preencher um checklist de prompt no papel.","reflection":"Qual alteração produziu a maior melhoria e como você percebeu isso?","tools":"Editor de texto e ferramenta de IA, com alternativa em papel.","requirements":[["text",true,"Histórico do prompt: original, v1, v2 e v3 identificados."],["text",true,"Amostra de respostas: síntese do resultado de cada versão."],["text",true,"Análise da iteração: qual mudança teve maior efeito e por quê."]],"criteria":["A v3 informa o contexto.","A v3 declara um objetivo específico.","A v3 contém pelo menos uma restrição.","A v3 define o formato esperado da resposta.","A análise compara a v3 com uma versão anterior."]},
 {"position":4,"title":"Project Day: Meu Assistente Inteligente","challenge":"Entregar um assistente de escopo pequeno que responda de modo consistente, reconheça limites e melhore após testes.","context":"Este Project Day consolida as três atividades anteriores. O valor está em ter propósito, instrução, teste e melhoria demonstráveis, não em criar um assistente que ‘faz tudo’.","objective":"Construir, testar, corrigir, documentar e apresentar o Projeto 1.","steps":["Definir nome, problema, público, objetivo, personalidade e limites.","Finalizar o prompt principal.","Criar três exemplos de entrada e saída esperada.","Executar cinco testes.","Corrigir pelo menos uma falha encontrada.","Documentar e apresentar em até três minutos."],"continuity":"Registrar uma limitação e uma melhoria futura no dossiê do Projeto 1; a próxima atividade inicia um novo ciclo, reutilizando o hábito de variar um elemento por vez.","evidence":"Página ‘Meu Assistente Inteligente’ com ficha, prompt, exemplos, testes, melhoria e demonstração opcional.","planB":"Demonstrar com respostas salvas, apresentar o prompt e o roteiro de testes e concluir a execução quando a ferramenta voltar.","reflection":"Que teste mudou o assistente e qual limitação ainda permanece?","tools":"Ferramenta de IA, documento e gravação opcional.","requirements":[["text",true,"Ficha do assistente: nome, problema, público, objetivo, personalidade e limites."],["text",true,"Prompt principal: versão final completa."],["text",true,"Exemplos: três pares de entrada e saída esperada."],["text",true,"Relatório de testes: cinco testes, resultado e falhas encontradas."],["text",true,"Melhoria aplicada: mudança realizada e motivo."],["external_link",false,"Demonstração gravada: URL HTTPS acessível ao professor."]],"criteria":["O assistente resolve um problema específico para um público definido.","O prompt principal contém papel, objetivo, tom e limites.","Existem exatamente três exemplos de interação.","Existem exatamente cinco testes registrados.","Pelo menos uma alteração decorre de um teste.","O aluno consegue explicar o assistente em até três minutos."]},
 {"position":5,"title":"Três direções para uma imagem","challenge":"Gerar três versões da mesma ideia, alterando somente um elemento visual por vez, e selecionar a que melhor comunica a intenção.","context":"Criação visual com IA exige direção e curadoria. Uma sequência controlada permite distinguir escolha intencional de geração aleatória.","objective":"Experimentar estilo, luz, cenário ou composição e justificar uma escolha visual.","steps":["Definir a ideia, o público e a mensagem.","Escrever um prompt-base.","Gerar ou planejar três versões.","Alterar somente um elemento visual por vez.","Comparar as versões.","Escolher uma direção e indicar o próximo ajuste."],"continuity":"Levar a imagem escolhida, o público e a mensagem pretendida para compor o brief da Atividade 6.","evidence":"Estudo ‘Exploração visual com IA’, mostrando processo, não apenas a imagem final.","planB":"Montar um moodboard com imagens existentes, comparar referências fornecidas ou escrever os três prompts para geração posterior.","reflection":"Qual escolha visual comunica melhor a intenção e por quê?","tools":"Gerador de imagens, editor visual ou moodboard.","requirements":[["file",true,"Grade visual: arquivo único com as três versões identificadas como A, B e C."],["text",true,"Prompts: prompt-base e alteração feita em cada variação."],["text",true,"Curadoria: versão escolhida, justificativa e próximo ajuste."]],"criteria":["A grade contém três versões da mesma ideia.","Cada variação muda um elemento visual identificável.","Os prompts permitem reconhecer o elemento alterado.","A justificativa cita pelo menos um aspecto visual concreto.","A versão escolhida se relaciona à mensagem pretendida."]},
 {"position":6,"title":"Brief de campanha que comunica","challenge":"Transformar a direção visual escolhida em uma campanha com público, mensagem, slogan, copy e tom coerentes.","context":"Estética sem público e mensagem não constitui comunicação. O brief liga intenção, linguagem e peça antes da produção de vídeo.","objective":"Definir o conceito criativo completo do Projeto 2.","steps":["Nomear a campanha e a oferta ou ideia.","Definir o público.","Escrever a mensagem central em uma frase.","Definir estilo visual e tom.","Criar slogan e copy curta.","Selecionar ou ajustar a imagem principal.","Revisar a coerência do conjunto."],"continuity":"Preparar para a Atividade 7 uma referência de vídeo, um clima de áudio e a frase que precisa permanecer compreensível na peça.","evidence":"Brief ‘Conceito criativo da campanha’, acompanhado da imagem principal.","planB":"Criar o brief no papel ou em slides e usar imagens previamente baixadas ou a grade da Atividade 5.","reflection":"Que decisão torna mensagem, público e imagem mais coerentes entre si?","tools":"Documento, slides e editor visual opcional.","requirements":[["text",true,"Brief criativo: nome, oferta ou ideia, público, mensagem, estilo e tom."],["text",true,"Slogan e copy: slogan e texto curto da peça."],["file",true,"Imagem principal: arquivo visual selecionado ou composto."]],"criteria":["O público está descrito de forma específica.","A mensagem central cabe em uma frase.","O slogan se relaciona à mensagem central.","A copy é adequada ao público definido.","A imagem principal sustenta a mensagem da campanha."]},
 {"position":7,"title":"Vídeo curto: roteiro à primeira versão","challenge":"Transformar o brief em uma peça de 15 a 30 segundos com começo, meio e fim, sem perder a mensagem em efeitos.","context":"Vídeo combina sequência, ritmo, imagem e som. Uma peça simples e compreensível gera melhor evidência que uma produção sofisticada incompleta.","objective":"Produzir uma primeira versão assistível ou um storyboard temporal completo da campanha.","steps":["Definir começo, meio e fim.","Escrever cenas com duração, ação visual e áudio.","Montar vídeo ou storyboard temporal.","Inserir a copy da campanha.","Verificar duração e compreensão.","Compartilhar a primeira versão."],"continuity":"Listar ajustes de imagem, áudio, ritmo e copy que serão concluídos no Project Day.","evidence":"Primeira versão do vídeo e roteiro, preservando a evolução até a peça final.","planB":"Criar storyboard compartilhável em slides, usar imagens estáticas com transições ou gravar narração sobre a apresentação.","reflection":"O que ainda precisa mudar para a mensagem ser entendida sem explicação longa?","tools":"Editor de vídeo, slides ou storyboard.","requirements":[["text",true,"Roteiro temporal: cenas, duração, ação visual e áudio."],["external_link",true,"Primeira versão: link HTTPS para vídeo ou storyboard compartilhável."],["text",true,"Copy da peça: textos usados na tela ou na narração."],["file",false,"Backup: exportação leve, storyboard em PDF ou frame-chave."]],"criteria":["O roteiro contém início, desenvolvimento e encerramento.","A duração planejada está entre 15 e 30 segundos.","O link abre sem solicitar permissão adicional ao professor.","Imagem e áudio sustentam a mesma mensagem.","A peça comunica a campanha sem explicação externa longa."]},
 {"position":8,"title":"Project Day: Creative Studio","challenge":"Finalizar e apresentar uma campanha autoral cuja imagem, peça, copy e processo comuniquem a mesma ideia.","context":"Este Project Day consolida direção visual, brief e vídeo. O padrão de qualidade é clareza e coerência; perfeccionismo estético não deve impedir a entrega.","objective":"Concluir, documentar e apresentar o Projeto 2.","steps":["Revisar o brief e a mensagem central.","Finalizar a imagem principal.","Finalizar vídeo ou storyboard.","Revisar slogan e copy.","Documentar prompts, escolhas e ajustes.","Apresentar em até três minutos."],"continuity":"Publicar a página do Projeto 2 no portfólio e levar para o ciclo seguinte uma tarefa repetitiva real que possa ser representada como fluxo.","evidence":"Página ‘Creative Studio’ com imagem, peça audiovisual, copy e bastidores do processo.","planB":"Entregar imagem, storyboard e roteiro; usar slides narrados ou demonstrar a peça offline com arquivo exportado.","reflection":"Qual decisão de curadoria mais fortaleceu a campanha?","tools":"Editor visual, vídeo ou slides e documento.","requirements":[["text",true,"Resumo da campanha: nome, objetivo, público e mensagem."],["file",true,"Imagem final: arquivo pronto para exibição."],["external_link",true,"Peça audiovisual: vídeo ou storyboard compartilhável."],["text",true,"Copy final: slogan e texto da peça."],["text",true,"Processo criativo: prompts, escolha principal e melhoria realizada."]],"criteria":["O resumo identifica público e mensagem.","A imagem final está legível e completa.","A peça audiovisual abre pelo link informado.","A copy final é coerente com o brief.","O processo registra pelo menos uma decisão de curadoria.","O aluno apresenta a campanha em até três minutos."]},
 {"position":9,"title":"Raio-X de uma automação","challenge":"Representar uma tarefa repetitiva como entrada, processamento, decisão e saída antes de abrir uma ferramenta de automação.","context":"Automação começa pela compreensão do processo. Um fluxo que não pode ser explicado no papel também será difícil de construir e testar no n8n.","objective":"Desenhar um fluxo simples e explicar para quem ele gera valor.","steps":["Escolher uma tarefa repetitiva real.","Identificar o evento ou dado de entrada.","Descrever o processamento.","Acrescentar uma decisão somente se necessária.","Definir saída e usuário beneficiado.","Resumir o valor do fluxo em uma frase."],"continuity":"Escolher a versão mínima do fluxo, sem decisões desnecessárias, para implementar na Atividade 10.","evidence":"Primeiro diagrama de automação acompanhado da explicação de valor.","planB":"Desenhar com papel, post-its ou quadro e fotografar; construir um fluxo coletivo se o aluno ainda não encontrar um caso próprio.","reflection":"Qual etapa é indispensável para o fluxo gerar valor?","tools":"Papel, quadro ou ferramenta de diagrama.","requirements":[["file",true,"Diagrama do fluxo: foto legível ou arquivo exportado."],["text",true,"Ficha do processo: frequência, entrada, processamento, saída e usuário."],["text",true,"Frase de valor: ‘Este fluxo ajuda X a Y porque Z’. "]],"criteria":["O fluxo possui uma entrada identificada.","O fluxo possui um processamento identificável.","O fluxo possui uma saída identificada.","O usuário beneficiado está nomeado.","A frase de valor corresponde ao fluxo desenhado."]},
 {"position":10,"title":"Primeiro workflow em execução","challenge":"Transformar o diagrama em um workflow mínimo com gatilho, processamento e saída realmente executados.","context":"O objetivo não é aprender toda a ferramenta, mas observar uma ação acontecendo de ponta a ponta e saber explicar os dados em cada etapa.","objective":"Construir e testar um workflow básico no n8n ou alternativa disponível.","steps":["Criar o gatilho por formulário, execução manual ou webhook.","Adicionar um processamento simples.","Configurar uma saída observável.","Executar um caso de teste.","Registrar o fluxo e o resultado."],"continuity":"Identificar uma etapa em que classificação, resumo ou geração por IA agregaria valor ao workflow da Atividade 11.","evidence":"Print do primeiro workflow executado, com legenda de entrada, processamento e saída.","planB":"Usar o ambiente central do professor, duplicar um template, simular com formulário e planilha ou registrar a execução guiada em dupla.","reflection":"Que dado entrou, como foi processado e qual saída comprovou a execução?","tools":"n8n ou alternativa de automação; simulação permitida.","requirements":[["external_link",false,"Workflow compartilhado: URL HTTPS do fluxo quando o ambiente permitir compartilhamento."],["file",true,"Print da execução: visão do fluxo executado sem credenciais ou dados pessoais."],["text",true,"Explicação dos nós: o que cada etapa recebe, faz e entrega."],["text",true,"Caso de teste: entrada utilizada e saída obtida."]],"criteria":["Existe um gatilho configurado.","Existe uma etapa de processamento.","Existe uma saída observável.","O caso de teste chegou até a saída.","A explicação descreve cada etapa sem expor segredo."]},
 {"position":11,"title":"IA como etapa do fluxo","challenge":"Inserir uma etapa de IA que receba uma entrada definida, produza uma resposta previsível e determine a ação seguinte.","context":"Colocar IA dentro de um processo é diferente de conversar livremente com um chatbot. O fluxo precisa controlar entrada, prompt, formato da resposta e destino do resultado.","objective":"Construir ou simular um workflow em que a IA analise, classifique, resuma ou gere uma saída utilizada pela automação.","steps":["Definir a entrada que chegará à IA.","Escrever um prompt curto com formato de saída previsível.","Ligar a resposta a uma condição ou próxima ação.","Executar um teste.","Registrar entrada, resposta e saída final."],"continuity":"Escolher o problema pequeno que será resolvido no Project Day e preparar um teste de sucesso e um teste de falha.","evidence":"Comparação ‘chat isolado vs. IA no processo’, ilustrada pelo fluxo e pelo caso de teste.","planB":"Usar uma resposta mockada no lugar da API, executar a etapa de IA manualmente e manter o restante do fluxo e da documentação verificáveis.","reflection":"Como o formato da resposta da IA controla a próxima ação do fluxo?","tools":"n8n, IA ou resposta mockada.","requirements":[["file",true,"Fluxo com IA: print ou diagrama indicando a etapa de IA."],["text",true,"Prompt da automação: instrução completa usada no nó ou na simulação."],["text",true,"Registro do teste: entrada, resposta da IA e ação seguinte."],["external_link",false,"Workflow compartilhado: URL HTTPS quando disponível."]],"criteria":["A entrada recebida pela IA está definida.","O prompt especifica o formato da resposta.","A resposta da IA está registrada.","O fluxo define uma ação posterior à resposta.","O teste demonstra a passagem da entrada até a saída final."]},
 {"position":12,"title":"Project Day: Automation Lab","challenge":"Entregar uma automação real ou simulada que resolva um problema pequeno de ponta a ponta e sobreviva a uma demonstração.","context":"Este Project Day consolida diagrama, workflow e IA no processo. Problema pequeno resolvido tem mais valor pedagógico que fluxo grande e inacabado.","objective":"Concluir, testar, documentar e apresentar o Projeto 3.","steps":["Declarar problema, usuário e resultado esperado.","Revisar o diagrama e montar o workflow mínimo.","Executar um caso de sucesso.","Executar ou descrever um caso de falha seguro.","Registrar resultado e limitações.","Preparar uma demonstração curta."],"continuity":"Publicar a página do Projeto 3 e observar um problema real que possa originar o AI Product do ciclo final.","evidence":"Página ‘Automation Lab’ com problema, diagrama, execução, resultado e demonstração opcional.","planB":"Entregar diagrama completo, prompt, resposta mockada, fluxo parcial e vídeo ou roteiro que explique a simulação.","reflection":"Que limitação apareceu no teste e como ela restringe o uso da automação?","tools":"n8n, diagrama, documento e demonstração opcional.","requirements":[["text",true,"Ficha da automação: problema, usuário, entrada e saída esperada."],["file",true,"Diagrama final: fluxo completo e legível."],["file",true,"Evidência de execução: print do caso de sucesso sem dados sensíveis."],["text",true,"Teste e resultado: entrada usada, saída obtida e limitação encontrada."],["external_link",false,"Demonstração: workflow compartilhado ou vídeo curto."]],"criteria":["O problema resolvido está descrito em uma frase.","O diagrama representa entrada, processamento e saída.","A evidência mostra uma execução concluída.","O resultado do teste corresponde ao objetivo declarado.","Pelo menos uma limitação está documentada.","O aluno consegue explicar o fluxo de ponta a ponta."]},
 {"position":13,"title":"Product Brief: problema antes da solução","challenge":"Investigar uma necessidade real e reduzir a ideia a um produto demonstrável em uma semana.","context":"Produto começa no problema e no usuário, não na ferramenta. Uma conversa curta com alguém afetado evita construir apenas a partir de suposições.","objective":"Definir problema, usuário, solução, papel da IA e limites do MVP do Projeto 4.","steps":["Descrever o problema e quem o enfrenta.","Registrar como a pessoa resolve isso hoje.","Conversar com pelo menos uma pessoa real ou analisar um relato fornecido pelo professor.","Propor a solução e onde a IA entra.","Definir entrada, saída e forma de demonstração.","Fixar o que entra e o que fica fora do MVP de uma semana."],"continuity":"Levar para a Atividade 14 apenas o fluxo mínimo necessário para demonstrar a promessa central do Product Brief.","evidence":"Documento ‘Definição do problema do AI Product’, incluindo a descoberta que alterou a ideia.","planB":"Usar entrevista em dupla, relato fornecido pelo professor, post-its e template impresso; nenhuma ferramenta digital é necessária.","reflection":"Qual descoberta sobre o usuário mudou sua ideia inicial?","tools":"Entrevista, relato, post-its ou documento.","requirements":[["text",true,"Product Brief: problema, usuário, solução atual, proposta, IA, entrada, saída e demo."],["text",true,"Registro de descoberta: pessoa ou perfil consultado, três aprendizados e uma mudança provocada pela conversa."],["text",true,"Escopo do MVP: itens ‘entra’ e ‘fica fora’. "]],"criteria":["O problema está descrito sem mencionar uma ferramenta como solução.","O usuário afetado está identificado.","O registro contém evidência de uma conversa ou relato real.","O papel da IA está explicitado.","A demonstração esperada está definida.","O escopo separa o que entra do que fica fora."]},
 {"position":14,"title":"Blueprint da solução","challenge":"Desenhar o caminho completo do usuário e localizar exatamente onde IA ou automação participa.","context":"Wireframe e fluxo reduzem retrabalho antes do Build Day. O desenho deve priorizar compreensão funcional: feio e claro vence bonito e confuso.","objective":"Produzir o blueprint do MVP com entrada, processamento, resultado e demonstração.","steps":["Desenhar o ponto inicial do usuário.","Desenhar a informação fornecida pelo usuário.","Representar o processamento e a etapa de IA ou automação.","Desenhar o resultado recebido.","Marcar o caminho da demonstração.","Listar materiais e backups necessários para construir."],"continuity":"Iniciar o Build Day pelo caminho mínimo da demo, deixando elementos decorativos e funcionalidades extras para depois.","evidence":"Wireframe e diagrama ‘Como o AI Product funciona’.","planB":"Desenhar em papel, fotografar e escrever o roteiro; ferramenta de prototipação digital é opcional.","reflection":"Qual é o caminho mínimo que ainda demonstra a promessa central?","tools":"Papel, ferramenta de wireframe ou diagrama.","requirements":[["file",true,"Wireframe: telas ou estados essenciais do MVP."],["file",true,"Fluxo do produto: usuário, entrada, processamento, IA e resultado."],["text",true,"Plano de build: núcleo, materiais, ferramentas, evidências e backup."],["text",true,"Roteiro da demo: sequência que será apresentada."]],"criteria":["O wireframe mostra o ponto de entrada.","O fluxo mostra o dado fornecido pelo usuário.","O fluxo identifica a etapa de IA ou automação.","O resultado entregue ao usuário está representado.","O roteiro permite demonstrar a promessa central.","O plano inclui um backup executável no tempo disponível."]},
 {"position":15,"title":"Build Day: AI Product","challenge":"Construir primeiro o núcleo demonstrável do produto e cortar qualquer extra que ameace a entrega.","context":"O AI Product pode combinar prompt, mídia, formulário, página, automação ou código. O critério comum é demonstrar a solução; GitHub só é pertinente quando existe um repositório real.","objective":"Produzir, testar e documentar uma versão funcional ou demonstrável do Projeto 4.","steps":["Construir o caminho mínimo definido no blueprint.","Testar uma entrada representativa.","Conferir se o resultado demonstra a promessa central.","Reduzir escopo quando algo não funcionar.","Capturar evidências e documentar limitações.","Ensaiar a apresentação de cinco minutos."],"continuity":"Congelar o núcleo, corrigir apenas bloqueadores, salvar backup offline e preparar problema, solução, demo e aprendizado para o Demo Day.","evidence":"Versão do MVP, evidência de teste, documentação, link e repositório opcional.","planB":"Demonstrar com formulário e operação manual, slides navegáveis, protótipo, automação parcial, vídeo simulado ou fluxo acompanhado de exemplo real de saída.","reflection":"Que corte de escopo protegeu a promessa central do produto?","tools":"Ferramentas adequadas ao MVP; GitHub somente quando houver repositório real.","requirements":[["external_link",true,"Demo do MVP: página, automação, formulário, protótipo ou vídeo compartilhável."],["text",true,"Documentação do produto: problema, solução, uso, ferramentas e limitações."],["file",true,"Evidência de teste: print ou PDF da entrada e do resultado."],["text",true,"Registro de escopo: o que foi cortado e por quê."],["github_repository",false,"Repositório do produto: URL pública ou autorizada do GitHub quando houver código ou versionamento."]],"criteria":["A demo abre sem depender da conta pessoal do professor.","A demo apresenta uma entrada ou ação do usuário.","A demo apresenta um resultado relacionado ao problema.","A evidência registra pelo menos um teste concluído.","A documentação declara uma limitação real.","O registro identifica pelo menos um corte de escopo consciente.","Quando enviado, o repositório corresponde ao produto demonstrado."]},
 {"position":16,"title":"Demo Day: eu construí isto","challenge":"Apresentar o AI Product e provar a evolução ao longo dos quatro projetos sem depender integralmente da internet.","context":"Demo Day é um ritual de evidência, não uma prova de perfeição. A apresentação deve tornar visíveis problema, solução, funcionamento e aprendizado, com backup pronto.","objective":"Apresentar o Projeto 4, consolidar o portfólio do Explorer e registrar a reflexão final.","steps":["Apresentar o problema em até um minuto.","Apresentar a solução em até um minuto.","Demonstrar o produto em até dois minutos.","Explicar o principal aprendizado em até um minuto.","Usar o backup se a demonstração ao vivo falhar.","Publicar o portfólio e registrar a reflexão final."],"continuity":"Registrar o interesse para o Builder, preservar os links e backups e transformar o feedback do professor em uma próxima melhoria opcional, sem reabrir a conclusão do Explorer.","evidence":"Portfólio final, slides, registro da apresentação, feedback do professor e reflexão de evolução.","planB":"Apresentar vídeo gravado, prints, PDF ou demonstração simulada com roteiro; nunca depender exclusivamente de conexão ou serviço externo.","reflection":"Qual foi sua maior evolução, sua principal dificuldade e o próximo interesse que quer explorar?","tools":"Portfólio, slides, backup offline e gravação opcional.","requirements":[["external_link",true,"Portfólio Explorer: URL com os quatro projetos."],["file",true,"Backup da apresentação: slides em PDF, prints ou arquivo equivalente."],["external_link",false,"Registro do Demo Day: vídeo da apresentação ou demonstração."],["text",true,"Reflexão final: dificuldade, melhoria, maior aprendizado e próximo interesse."],["github_repository",false,"Repositório final: quando o AI Product possuir código."]],"criteria":["A apresentação identifica o problema.","A apresentação explica a solução.","A demonstração mostra o resultado do produto.","A fala respeita o limite de cinco minutos.","O portfólio contém evidência do Projeto 1.","O portfólio contém evidência do Projeto 2.","O portfólio contém evidência do Projeto 3.","O portfólio contém evidência do Projeto 4.","Existe um backup utilizável sem a demo ao vivo.","A reflexão responde às quatro perguntas solicitadas."]}
]
$json$::jsonb);

with operational_tenant as (
  select id from logos_academy.tenants where slug='logos-academy' and deleted_at is null
), activities as (
  select value d from explorer_v2_activities cross join lateral jsonb_array_elements(payload)
)
insert into logos_academy.lesson_templates (
  id,tenant_id,cycle_id,position,title,objective,reference_content,estimated_activity_minutes
)
select md5('logos-academy-explorer-v2-lesson-'||(d->>'position'))::uuid,t.id,
  md5('logos-academy-explorer-v2-cycle-'||(((d->>'position')::int-1)/4+1))::uuid,
  (((d->>'position')::int-1)%4+1)::smallint,d->>'title',d->>'objective',d->>'context',
  case when (d->>'position')::int in (4,8,12,16) then 45 else 25 end
from operational_tenant t cross join activities
on conflict do nothing;

with operational_tenant as (
  select id from logos_academy.tenants where slug='logos-academy' and deleted_at is null
), activities as (
  select value d from explorer_v2_activities cross join lateral jsonb_array_elements(payload)
)
insert into logos_academy.lesson_concepts (id,tenant_id,lesson_template_id,concept_id)
select md5('logos-academy-explorer-v2-lesson-concept-'||(d->>'position'))::uuid,t.id,
  md5('logos-academy-explorer-v2-lesson-'||(d->>'position'))::uuid,
  md5('logos-academy-explorer-v1-concept-'||(d->>'position'))::uuid
from operational_tenant t cross join activities
on conflict do nothing;

with operational_tenant as (
  select id from logos_academy.tenants where slug='logos-academy' and deleted_at is null
), activities as (
  select value d from explorer_v2_activities cross join lateral jsonb_array_elements(payload)
)
insert into logos_academy.activity_templates (
  id,tenant_id,lesson_template_id,title,objective,instructions,continuity_guidance,estimated_minutes,
  context,expected_result,steps,plan_b,reflection_prompt,portfolio_evidence,tool_hint
)
select md5('logos-academy-explorer-v2-activity-'||(d->>'position'))::uuid,t.id,
  md5('logos-academy-explorer-v2-lesson-'||(d->>'position'))::uuid,d->>'title',d->>'objective',
  d->>'challenge',d->>'continuity',case when (d->>'position')::int in (4,8,12,16) then 45 else 25 end,
  d->>'context',d->>'evidence',d->'steps',d->>'planB',d->>'reflection',d->>'evidence',d->>'tools'
from operational_tenant t cross join activities
on conflict do nothing;

with operational_tenant as (
  select id from logos_academy.tenants where slug='logos-academy' and deleted_at is null
), activities as (
  select value d from explorer_v2_activities cross join lateral jsonb_array_elements(payload)
), requirements as (
  select d,(ordinality)::smallint position,value requirement
  from activities cross join lateral jsonb_array_elements(d->'requirements') with ordinality
)
insert into logos_academy.activity_requirements (id,tenant_id,activity_template_id,kind,label,is_required,position)
select md5('logos-academy-explorer-v2-requirement-'||(d->>'position')||'-'||position)::uuid,t.id,
  md5('logos-academy-explorer-v2-activity-'||(d->>'position'))::uuid,
  requirement->>0,requirement->>2,(requirement->>1)::boolean,position
from operational_tenant t cross join requirements
on conflict do nothing;

with operational_tenant as (
  select id from logos_academy.tenants where slug='logos-academy' and deleted_at is null
), activities as (
  select value d from explorer_v2_activities cross join lateral jsonb_array_elements(payload)
), criteria as (
  select d,(ordinality)::smallint position,value #>> '{}' criterion
  from activities cross join lateral jsonb_array_elements(d->'criteria') with ordinality
)
insert into logos_academy.activity_criteria (id,tenant_id,activity_template_id,label,description,position)
select md5('logos-academy-explorer-v2-criterion-'||(d->>'position')||'-'||position)::uuid,t.id,
  md5('logos-academy-explorer-v2-activity-'||(d->>'position'))::uuid,
  criterion,criterion,position
from operational_tenant t cross join criteria
on conflict do nothing;

-- Publication boundary: old rows keep working, but new classes/enrollments cannot target v1.
create or replace function private.guard_explorer_v1_new_placement()
returns trigger language plpgsql set search_path='' as $$
begin
  if new.curriculum_id = md5('logos-academy-explorer-v1-curriculum')::uuid then
    raise exception using errcode='23514',message='Explorer v1 no longer accepts new classes or enrollments';
  end if;
  return new;
end;
$$;

drop trigger if exists classes_explorer_v1_new_placement on logos_academy.classes;
create trigger classes_explorer_v1_new_placement before insert on logos_academy.classes
for each row execute function private.guard_explorer_v1_new_placement();
drop trigger if exists enrollments_explorer_v1_new_placement on logos_academy.enrollments;
create trigger enrollments_explorer_v1_new_placement before insert on logos_academy.enrollments
for each row execute function private.guard_explorer_v1_new_placement();

revoke all on function private.guard_explorer_v1_new_placement() from public,anon,authenticated;

notify pgrst,'reload schema';
commit;
