begin;

-- O Explorer v3 passa a ser uma trilha de quatro projetos completos. Os IDs
-- existentes permanecem estáveis para não romper turmas ou dossiês já criados.
with data as (
  select * from jsonb_to_recordset($cycles$[
    {
      "position": 1,
      "title": "Assistente Pessoal Inteligente",
      "project_title": "Assistente Pessoal Inteligente",
      "project_challenge": "Criar um assistente especializado, útil e autoral para uma necessidade real, com três modos ou especialidades, IA segura, memória controlada, respostas estruturadas e experiência publicada.",
      "project_problem": "Pessoas recebem respostas genéricas de ferramentas de IA e precisam de uma experiência que compreenda um contexto específico, respeite limites e ajude a avançar sem substituir sua autonomia.",
      "project_audience": "Um grupo definido pelo aluno. O professor particular com especialistas em Matemática, Português e História é o exemplo para quem não escolher outro tema.",
      "project_expected_result": "Aplicação web responsiva publicada, com rota Groq server-side, modelo principal e fallback, três modos ou personas, instrução complementar, histórico, contexto limitado, rate limit, recurso visual seguro, testes e documentação.",
      "project_quality_criteria": ["Propósito e público claros", "Três modos ou especialidades coerentes", "Segredo protegido e fallback funcional", "Memória, contexto e rate limit controlados", "Resposta estruturada e recurso visual seguro", "Cinco testes, deploy e decisões documentadas"],
      "project_concepts": ["Experiência conversacional", "System prompt", "Personas e modos", "Saída estruturada", "Memória e contexto", "Fallback", "Rate limit", "Teste e deploy"]
    },
    {
      "position": 2,
      "title": "Creative Studio",
      "project_title": "Creative Studio",
      "project_challenge": "Transformar um brief em uma campanha digital coerente, autoral e publicada, conectando estratégia, identidade, peças multiformato, landing page, movimento e narrativa audiovisual.",
      "project_problem": "Conteúdo gerado sem direção produz peças bonitas, porém desconectadas do público, da mensagem e umas das outras.",
      "project_audience": "Público de uma marca, causa, evento, produto, jogo ou projeto escolhido pelo aluno.",
      "project_expected_result": "Campanha digital publicada com brief, três direções comparadas, sistema visual, peças em formatos distintos, copies, landing page responsiva, vídeo ou storyboard e registro de prompts, curadoria e melhorias.",
      "project_quality_criteria": ["Brief orienta todas as decisões", "Sistema visual consistente e acessível", "Peças e copies adaptadas aos canais", "Landing responsiva com CTA e movimento significativo", "Vídeo ou storyboard sustenta a narrativa", "Processo, descartes e revisão estão documentados"],
      "project_concepts": ["Brief criativo", "Direção de arte", "Sistema visual", "Prompt e curadoria", "Copy", "Landing page", "Motion", "Storytelling audiovisual"]
    },
    {
      "position": 3,
      "title": "Automation Lab",
      "project_title": "Automation Lab",
      "project_challenge": "Automatizar um processo manual real do início ao fim, com entrada validada, regras, IA delimitada, revisão humana, saída útil, persistência, recuperação de falhas e rastreabilidade.",
      "project_problem": "Processos repetitivos consomem tempo, geram erros e perdem contexto quando não há contrato de dados, estados ou tratamento das exceções.",
      "project_audience": "Pessoa, equipe, escola, negócio ou comunidade que hoje executa manualmente o processo escolhido.",
      "project_expected_result": "Workflow executável com formulário ou webhook, validação, armazenamento, regras, etapa de IA estruturada, confiança, revisão humana, idempotência, retry, logs, saída útil e cinco cenários testados.",
      "project_quality_criteria": ["Processo atual e futuro são compreensíveis", "Entrada validada e estados persistidos", "IA tem tarefa e saída delimitadas", "Exceções possuem revisão humana e recuperação", "Duplicidades e falhas não corrompem o fluxo", "Logs, testes e demonstração explicam o resultado"],
      "project_concepts": ["Mapeamento de processo", "Webhook e contrato de dados", "Validação", "Regras", "IA estruturada", "Human in the loop", "Idempotência", "Observabilidade"]
    },
    {
      "position": 4,
      "title": "MVP: Produto Inteligente",
      "project_title": "MVP: Produto Inteligente",
      "project_challenge": "Construir um produto novo que resolva um problema definido pelo aluno e combine, em um fluxo principal completo, IA especializada, experiência visual coerente e automação confiável.",
      "project_problem": "Uma ideia só vira produto quando entrega valor observável para alguém, integra suas partes e continua compreensível quando algo falha.",
      "project_audience": "Um usuário específico escolhido e investigado pelo aluno. Uma plataforma de organização de evento escolar é o exemplo de referência.",
      "project_expected_result": "MVP publicado com problema, hipótese e métrica explícitos; interface responsiva; IA com regras e fallback; dados e automação; segurança, estados e recuperação; cinco testes ponta a ponta; documentação e Demo Day.",
      "project_quality_criteria": ["Problema, usuário e promessa são específicos", "Um fluxo principal entrega valor de ponta a ponta", "IA, interface e automação são indispensáveis ao mesmo fluxo", "Segredos, entradas, limites e falhas estão protegidos", "Teste externo gera ao menos uma melhoria", "Deploy, arquitetura e apresentação são explicáveis"],
      "project_concepts": ["Descoberta de produto", "Hipótese e métrica", "Prototipação", "Experiência responsiva", "IA aplicada", "Automação", "Confiabilidade", "Demo Day"]
    }
  ]$cycles$::jsonb) as x(
    position smallint,
    title text,
    project_title text,
    project_challenge text,
    project_problem text,
    project_audience text,
    project_expected_result text,
    project_quality_criteria text[],
    project_concepts text[]
  )
)
update logos_academy.cycles c set
  title = d.title,
  project_title = d.project_title,
  project_challenge = d.project_challenge,
  project_problem = d.project_problem,
  project_audience = d.project_audience,
  project_expected_result = d.project_expected_result,
  project_quality_criteria = d.project_quality_criteria,
  project_concepts = d.project_concepts,
  updated_at = now()
from data d
where c.id = md5('logos-academy-explorer-v3-cycle-' || d.position)::uuid;

with data as (
  select * from jsonb_to_recordset($lessons$[
    {"n":1,"title":"Produto, comportamento e interface do assistente","objective":"Definir a necessidade, o público e o contrato de comportamento do assistente e construir sua interface-base responsiva.","reference_content":"Escolha um problema específico e descreva o que o assistente faz, para quem, em quais modos e o que nunca deve fazer. Transforme esse contrato em uma jornada curta, estados de interface e uma direção visual autoral; orbe, avatar ou waveform são possibilidades, nunca requisitos."},
    {"n":2,"title":"Inteligência especializada e rota segura","objective":"Conectar a interface à Groq por uma rota server-side e implementar personas ou modos governados por um system prompt estruturado.","reference_content":"Separe instruções permanentes, escolha do usuário e mensagem atual. Proteja a chave no servidor, valide a entrada e peça uma saída previsível que a interface consiga renderizar. O exemplo professor usa Matemática, Português e História e orienta sem entregar a resposta."},
    {"n":3,"title":"Memória, recursos visuais e confiabilidade","objective":"Adicionar contexto controlado, histórico, resposta visual segura, fallback, rate limit e recuperação de falhas.","reference_content":"Memória útil não é enviar todo o histórico: selecione o que importa e limite o contexto. O modelo devolve dados estruturados e a aplicação renderiza componentes visuais conhecidos. Fallback, limites de uso e estados explícitos mantêm o assistente utilizável quando a resposta demora ou falha."},
    {"n":4,"title":"Project Day: Assistente Pessoal Inteligente","objective":"Integrar, testar, corrigir, documentar, publicar e demonstrar o assistente completo.","reference_content":"Releia o contrato do projeto, percorra o fluxo inteiro e execute a matriz de testes. Corrija a falha mais importante, documente arquitetura, decisões, limites e privacidade, publique e prepare uma demonstração curta. Não acrescente um recurso central novo neste encontro."},
    {"n":5,"title":"Brief e três direções criativas","objective":"Converter uma necessidade de comunicação em brief e comparar três direções antes de escolher uma.","reference_content":"Um brief define objetivo, público, mensagem, tom, canais, restrições e chamada para ação. Referências são analisadas, não copiadas. Três direções diferentes tornam a escolha justificável e evitam aceitar a primeira imagem gerada."},
    {"n":6,"title":"Sistema visual e peças multiformato","objective":"Construir a identidade escolhida e produzir peças coerentes para formatos e canais diferentes.","reference_content":"Transforme a direção em paleta, tipografia, componentes, composição e regras de uso. Documente prompts e critérios de curadoria. Adapte hierarquia, imagem e copy ao formato em vez de apenas redimensionar a mesma peça."},
    {"n":7,"title":"Landing, movimento e narrativa audiovisual","objective":"Conectar campanha, landing page e vídeo ou storyboard em uma experiência responsiva e acessível.","reference_content":"A landing organiza promessa, prova, narrativa e CTA. Movimento deve orientar atenção e respeitar preferência por redução. O vídeo ou storyboard combina gancho, cenas, ritmo, texto e áudio para contar a mesma história das peças."},
    {"n":8,"title":"Project Day: Creative Studio","objective":"Integrar, revisar, corrigir, publicar e apresentar a campanha como um sistema coerente.","reference_content":"Audite mensagem, identidade, peças, página e narrativa audiovisual como um conjunto. Corrija a incoerência de maior impacto, confira responsividade e acessibilidade, publique e apresente escolhas, descartes e evolução. Não introduza uma nova direção criativa."},
    {"n":9,"title":"Processo, gatilho e contrato de dados","objective":"Escolher um processo manual relevante e desenhar seu estado atual, estado futuro, gatilho e contrato de entrada.","reference_content":"Automatize uma dor observável, não uma sequência de ferramentas. Mapeie ator, entrada, decisão, saída e exceções. Defina dados obrigatórios, formatos válidos, consentimento e critério de sucesso antes de montar o workflow."},
    {"n":10,"title":"Workflow executável com regras e persistência","objective":"Construir o caminho feliz do workflow com validação, armazenamento, estados, regras e uma saída útil.","reference_content":"Receba dados por formulário ou webhook, valide-os e registre o estado do processamento. Use regras determinísticas para decisões previsíveis. Termine com uma consequência real, como tarefa, notificação, resposta ou atualização de registro."},
    {"n":11,"title":"IA delimitada, revisão humana e resiliência","objective":"Adicionar IA estruturada e tornar o fluxo seguro diante de incerteza, duplicidade e falha.","reference_content":"A IA executa uma tarefa pequena e retorna um formato validável com confiança ou justificativa. Casos incertos seguem para revisão humana. Chave de idempotência, retry controlado e logs evitam duplicidade, perda silenciosa e diagnóstico por adivinhação."},
    {"n":12,"title":"Project Day: Automation Lab","objective":"Testar cenários, corrigir, documentar e demonstrar a automação completa com rastreabilidade.","reference_content":"Execute casos de sucesso, entrada inválida, baixa confiança, duplicidade e falha externa. Verifique saída, estado e log; corrija o problema mais grave. Prepare diagrama final, painel ou relatório e demonstração. Não acrescente uma integração central nova."},
    {"n":13,"title":"Descoberta e recorte do MVP","objective":"Definir usuário, problema, promessa, hipótese, métrica e um fluxo principal que combine as competências anteriores.","reference_content":"O MVP é um produto novo, não a soma visual dos três projetos. Escolha uma dor específica, formule uma hipótese testável e corte o escopo até restar um fluxo completo em que interface, IA e automação sejam necessárias. Prototipe antes de implementar."},
    {"n":14,"title":"Experiência, dados e estados do produto","objective":"Construir a identidade e a interface responsiva do fluxo principal, incluindo modelo de dados e estados essenciais.","reference_content":"A experiência precisa mostrar o valor antes da tecnologia. Defina hierarquia, componentes, navegação e estados vazio, carregando, sucesso e erro. Estruture apenas os dados necessários para sustentar o fluxo e o histórico do usuário."},
    {"n":15,"title":"IA, automação e confiabilidade integradas","objective":"Conectar IA, dados e automação ao fluxo principal com validação, segurança, fallback e observabilidade.","reference_content":"A entrada é validada antes da IA; a saída é estruturada antes de alterar dados ou disparar ações. Proteja segredos, limite uso, registre eventos úteis e ofereça recuperação. Teste a integração completa, não apenas cada parte isolada."},
    {"n":16,"title":"Demo Day: MVP publicado","objective":"Validar, melhorar, documentar, publicar e defender o produto em uma demonstração ponta a ponta.","reference_content":"Execute cinco cenários, teste com outra pessoa e implemente ao menos uma melhoria baseada na observação. Confirme segurança, estados e recuperação, finalize README e arquitetura, publique e apresente problema, fluxo, decisões, evidências e próximos passos. Não adicione núcleo novo."}
  ]$lessons$::jsonb) as x(n smallint, title text, objective text, reference_content text)
)
update logos_academy.lesson_templates l set
  title = d.title,
  objective = d.objective,
  reference_content = d.reference_content,
  estimated_activity_minutes = 45,
  updated_at = now()
from data d
where l.id = md5('logos-academy-explorer-v3-lesson-' || d.n)::uuid;

with data as (
  select * from jsonb_to_recordset($activities$[
    {"n":1,"title":"Contrato e interface do meu assistente","objective":"Escolher uma necessidade real e transformar o contrato do assistente em uma interface responsiva e autoral.","instructions":"Defina público, problema, promessa, três modos ou especialidades e comportamentos proibidos. Desenhe o fluxo principal e implemente a interface-base com entrada, seletor, instrução complementar e área de resposta. Inclua estados vazio e carregando. Um orbe, avatar, waveform ou outro elemento reativo pode enriquecer a experiência, mas não é obrigatório.","continuity_guidance":"Na próxima aula, essa interface receberá respostas reais por uma rota server-side e cada modo ganhará instruções próprias.","context":"Você pode criar um assistente para estudo, rotina, escrita, treino, criação ou outro tema. O professor particular é apenas o exemplo de referência.","expected_result":"Brief curto, contrato de comportamento, fluxo e primeira interface navegável em repositório.","steps":["Escolha usuário e problema específico","Defina promessa, três modos e limites","Desenhe o fluxo e os estados essenciais","Implemente a interface responsiva","Registre decisões e publique o repositório"],"plan_b":"Sem ambiente de código, entregue wireframe detalhado, mapa de estados e protótipo clicável com os mesmos campos.","reflection_prompt":"Qual decisão impede seu assistente de ser apenas um chat genérico?","portfolio_evidence":"Brief, contrato de comportamento, interface-base e repositório inicial.","tool_hint":"Editor de código, GitHub, navegador e ferramenta de prototipação opcional."},
    {"n":2,"title":"Cérebro especializado com Groq","objective":"Implementar a rota segura, os três modos e o system prompt com saída estruturada.","instructions":"Crie uma rota server-side para a Groq, valide entrada e mantenha a chave apenas em variável de ambiente. Implemente três personas, especialidades ou modos selecionáveis e uma instrução complementar do usuário. Escreva o system prompt com objetivo, limites, proibições e formato de saída. No exemplo professor, a IA orienta, pede tentativa e não entrega resposta pronta.","continuity_guidance":"Na próxima aula, a saída estruturada sustentará memória, recurso visual, fallback e tratamento de falhas.","context":"A interface envia intenção e contexto; o servidor combina esses dados com regras permanentes e conversa com o modelo.","expected_result":"Conversa funcional por rota segura, com modos distintos, prompt versionado e resposta previsível.","steps":["Defina o esquema da requisição e da resposta","Implemente e valide a rota server-side","Configure GROQ_API_KEY fora do código","Crie instruções para os três modos","Teste diferenças e recusas esperadas"],"plan_b":"Se a API estiver indisponível, use respostas fixture no mesmo esquema e demonstre a rota e o prompt sem expor segredo.","reflection_prompt":"Que regra permanece igual mesmo quando o usuário muda o modo ou acrescenta instruções?","portfolio_evidence":"Rota server-side, system prompt, esquema de saída e testes dos três modos.","tool_hint":"Groq, variável de ambiente, editor de código e cliente HTTP ou navegador."},
    {"n":3,"title":"Memória e confiabilidade do assistente","objective":"Tornar o assistente consistente, visual e resiliente sem perder controle sobre contexto ou uso.","instructions":"Implemente histórico persistente e envie ao modelo apenas uma janela controlada. Adicione modelo de fallback, rate limit server-side, estados de erro e nova tentativa. Faça a IA devolver uma especificação visual validada e renderize-a com componentes seguros da interface; nunca injete SVG arbitrário do modelo. Voz e animação reativa são opcionais e não podem quebrar o fluxo em texto.","continuity_guidance":"No Project Day, você integrará as partes, executará a matriz final, corrigirá e publicará.","context":"Confiabilidade inclui o que acontece quando o modelo principal falha, o limite é atingido ou o histórico cresce.","expected_result":"Assistente com histórico, contexto limitado, visual seguro, fallback, rate limit e estados completos.","steps":["Persista o histórico e limite o contexto enviado","Implemente modelo principal e fallback","Adicione rate limit e mensagens de recuperação","Valide e renderize ao menos um recurso visual","Teste carregamento, falha, limite e retomada"],"plan_b":"Se o provedor falhar, valide memória, limite, fallback e renderização com fixtures locais registradas.","reflection_prompt":"Que informação do histórico realmente melhora a próxima resposta e qual deve ficar de fora?","portfolio_evidence":"Versão resiliente, registro de arquitetura e evidências de falha e recuperação.","tool_hint":"Storage local ou banco já disponível, Groq, Zod e componentes visuais controlados."},
    {"n":4,"title":"Project Day: Assistente Pessoal Inteligente","objective":"Entregar um assistente completo, testado, explicável e publicado.","instructions":"Integre interface, modos, prompt, memória, visual e proteções. Execute no mínimo cinco testes: caminho feliz, regra proibida, troca de modo, fallback e rate limit ou contexto longo. Corrija a falha de maior impacto, finalize README com arquitetura, privacidade e limites, publique e prepare uma demonstração de três minutos.","continuity_guidance":"O projeto concluído entra no portfólio como prova de domínio de IA aplicada e experiência conversacional.","context":"Project Day é para consolidar e provar o que já foi construído, não para iniciar um recurso central.","expected_result":"Deploy acessível, repositório organizado, matriz de testes, documentação e demonstração funcional.","steps":["Releia o contrato e congele o escopo","Integre e percorra o fluxo completo","Execute e registre cinco testes","Corrija a falha prioritária","Documente, publique e ensaie a demonstração"],"plan_b":"Sem deploy, apresente execução local gravada, repositório completo e diagnóstico documentado do bloqueio.","reflection_prompt":"Qual teste mais aumentou sua confiança no assistente e que limite ainda permanece?","portfolio_evidence":"Link publicado, repositório, README, matriz de testes e demonstração.","tool_hint":"GitHub, Vercel, navegador e checklist de qualidade."},
    {"n":5,"title":"Brief e três caminhos criativos","objective":"Definir a campanha e comparar três direções antes de escolher uma.","instructions":"Escolha marca, causa, evento, produto ou projeto. Escreva brief com objetivo, público, mensagem, tom, canais, restrições e CTA. Monte referências comentadas e gere três direções realmente distintas, cada uma com conceito, paleta, tipografia, composição e exemplo. Compare com critérios e selecione uma direção justificadamente.","continuity_guidance":"A direção escolhida será transformada em sistema visual e peças multiformato na próxima aula.","context":"Creative Studio não é gerar imagens soltas: é dirigir uma comunicação coerente para alguém e com um objetivo.","expected_result":"Brief completo, painel de referências, três direções comparáveis e decisão registrada.","steps":["Defina objetivo, público e ação desejada","Colete e analise referências","Crie três conceitos visuais distintos","Prototipe uma peça por direção","Compare critérios e escolha uma direção"],"plan_b":"Sem geração de imagem, use colagem, formas, tipografia e banco de imagens permitido para materializar as direções.","reflection_prompt":"Qual critério fez você rejeitar uma direção visualmente atraente?","portfolio_evidence":"Brief, referências, três direções e matriz de decisão.","tool_hint":"Canva ou editor visual, ferramenta de IA generativa e documento de brief."},
    {"n":6,"title":"Sistema visual e kit de campanha","objective":"Converter a direção escolhida em identidade consistente e peças adaptadas a canais diferentes.","instructions":"Defina tokens de cor, tipografia, espaçamento, formas, tratamento de imagem e tom de voz. Documente prompts e curadoria. Produza ao menos três peças em formatos diferentes, com copy adequada a cada canal, mantendo reconhecimento sem apenas redimensionar o mesmo layout. Organize componentes reutilizáveis.","continuity_guidance":"Na próxima aula, o sistema sustentará a landing page e a narrativa audiovisual.","context":"Consistência vem de regras reutilizáveis; adaptação vem de respeitar o contexto de cada formato.","expected_result":"Mini design system, biblioteca de componentes, três peças finais e copies versionadas.","steps":["Extraia regras da direção escolhida","Crie tokens e componentes reutilizáveis","Documente prompts e seleção dos resultados","Produza três formatos com hierarquia própria","Revise unidade visual e clareza da copy"],"plan_b":"Sem gerador disponível, construa as peças com fotografia, ícones, formas e tipografia licenciados ou próprios.","reflection_prompt":"O que permanece constante e o que muda entre os formatos da campanha?","portfolio_evidence":"Guia visual, prompts, componentes, peças e copies finais.","tool_hint":"Figma, Canva ou editor equivalente; gerador de imagem opcional."},
    {"n":7,"title":"Landing e história em movimento","objective":"Transformar a campanha em uma experiência responsiva com CTA e narrativa audiovisual.","instructions":"Construa uma landing page com promessa, contexto, benefício, prova e CTA. Use movimento para orientar atenção, inclua preferência por redução e verifique contraste, foco e texto alternativo. Produza um vídeo curto ou storyboard completo com gancho, cenas, narração ou texto, ritmo e encerramento alinhados à campanha.","continuity_guidance":"No Project Day, todas as peças serão auditadas como um único sistema antes da publicação.","context":"A landing aprofunda a mensagem; o vídeo concentra a história. Ambos precisam parecer parte da mesma campanha.","expected_result":"Landing responsiva funcional e vídeo curto ou storyboard pronto para apresentação.","steps":["Organize a narrativa e o CTA da página","Implemente a landing responsiva","Adicione movimento significativo e reduced motion","Crie roteiro e plano de cenas","Produza vídeo ou storyboard e revise acessibilidade"],"plan_b":"Se não houver edição de vídeo, entregue storyboard completo com duração, áudio, texto e transições descritas.","reflection_prompt":"Que movimento ou cena ajuda o público a entender, e qual seria apenas decoração?","portfolio_evidence":"Landing, roteiro, vídeo ou storyboard e checklist de acessibilidade.","tool_hint":"Next.js ou HTML/CSS, editor visual, editor de vídeo e Lighthouse opcional."},
    {"n":8,"title":"Project Day: Creative Studio","objective":"Publicar e defender uma campanha consistente do brief à experiência final.","instructions":"Compare brief, identidade, peças, copies, landing e vídeo ou storyboard. Revise mensagem, coerência, responsividade, contraste e CTA. Peça que outra pessoa descreva o que entendeu, corrija a incoerência de maior impacto, publique a landing e organize o case com decisões, descartes e evolução.","continuity_guidance":"O case final entra no portfólio como prova de direção criativa, curadoria e construção de experiência.","context":"Project Day consolida o sistema existente; uma nova direção ou canal deve ficar para próximos passos.","expected_result":"Campanha publicada, case documentado, revisão externa e apresentação de três minutos.","steps":["Audite a campanha contra o brief","Teste página e peças em formatos reais","Colete leitura de outra pessoa","Corrija a principal incoerência","Publique e monte o case de apresentação"],"plan_b":"Sem publicação, entregue protótipo navegável, exportações finais e gravação do percurso com o bloqueio documentado.","reflection_prompt":"Que parte do sistema mais fortalece a mensagem e qual melhoria faria depois?","portfolio_evidence":"Link da campanha, peças, vídeo ou storyboard, case e registro da melhoria.","tool_hint":"Navegador, Vercel, editor visual e checklist de coerência."},
    {"n":9,"title":"Raio-X do processo e contrato de entrada","objective":"Escolher uma automação útil e projetar o processo, os dados e as exceções antes das ferramentas.","instructions":"Observe uma tarefa manual recorrente e registre frequência, atores, tempo, erros e risco. Desenhe processo atual e futuro. Defina gatilho por formulário ou webhook, campos, tipos, obrigatoriedade, consentimento, estados e critérios de sucesso. Liste exceções que não podem ser decididas automaticamente.","continuity_guidance":"Na próxima aula, esse contrato se tornará um workflow executável com persistência e saída real.","context":"A central inteligente de solicitações é o exemplo: recebe, valida, classifica, encaminha e registra pedidos.","expected_result":"Diagnóstico, diagramas atual/futuro, contrato de entrada e catálogo de exceções.","steps":["Escolha e meça o processo manual","Mapeie atores, etapas e falhas atuais","Desenhe o fluxo futuro e seu gatilho","Defina esquema, validações e estados","Separe decisões automáticas de revisão humana"],"plan_b":"Sem acesso ao processo real, entreviste alguém e use cinco registros fictícios claramente identificados.","reflection_prompt":"Que parte do processo não deveria ser automatizada sem supervisão?","portfolio_evidence":"Diagnóstico, dois diagramas, contrato de dados e critérios de sucesso.","tool_hint":"Whimsical, Excalidraw ou papel; formulário e planilha para amostras."},
    {"n":10,"title":"Workflow funcionando de ponta a ponta","objective":"Construir o caminho feliz com validação, persistência, regras e saída útil.","instructions":"Implemente o gatilho e valide cada campo antes de processar. Salve dados e estado, aplique regras determinísticas e gere uma consequência real: registro, tarefa, notificação, resposta ou atualização. Use dados de teste sem informação pessoal real e preserve identificador para rastrear a execução.","continuity_guidance":"Na próxima aula, a IA será adicionada somente onde há interpretação, junto de revisão humana e recuperação.","context":"Um workflow confiável deixa visível o que entrou, qual regra decidiu, em que estado está e o que saiu.","expected_result":"Automação executável no caminho feliz, com dados validados, persistidos e rastreáveis.","steps":["Implemente formulário ou webhook","Valide e normalize a entrada","Persista registro e estado","Aplique regras determinísticas","Produza e confira a saída útil"],"plan_b":"Sem n8n disponível, simule o fluxo em código ou planilha com as mesmas entradas, regras, estados e saídas.","reflection_prompt":"Qual decisão ficou melhor como regra explícita do que como pedido para a IA?","portfolio_evidence":"Export do workflow, amostra de execução, esquema de dados e saída gerada.","tool_hint":"n8n, webhook, Supabase ou planilha e canal de saída escolhido."},
    {"n":11,"title":"IA com freios, retry e rastreabilidade","objective":"Adicionar inteligência delimitada e proteger o fluxo contra incerteza, duplicidade e falhas externas.","instructions":"Escolha uma única tarefa de interpretação para a IA e exija JSON validado com resultado, confiança e justificativa. Encaminhe baixa confiança ou casos sensíveis para revisão humana. Adicione chave de idempotência, retry limitado, caminho de erro e logs sem dados sensíveis. Prove que uma repetição não cria saída duplicada.","continuity_guidance":"No Project Day, cinco cenários validarão comportamento, recuperação e rastreabilidade do fluxo completo.","context":"IA amplia a automação quando sua responsabilidade é estreita e sua incerteza produz uma decisão segura.","expected_result":"Workflow com IA estruturada, revisão humana, deduplicação, retry e logs úteis.","steps":["Delimite a tarefa e o esquema da IA","Valide saída, confiança e justificativa","Crie fila ou estado de revisão humana","Implemente idempotência e retry controlado","Registre e teste falhas sem expor dados"],"plan_b":"Se a API falhar, use fixtures válidas, inválidas e ambíguas para testar todas as ramificações.","reflection_prompt":"Como o fluxo sabe que não deve confiar ou repetir uma ação?","portfolio_evidence":"Prompt, esquema, workflow revisado e evidências de revisão, duplicidade e recuperação.","tool_hint":"n8n, Groq, validador JSON e armazenamento de execuções."},
    {"n":12,"title":"Project Day: Automation Lab","objective":"Validar, corrigir, documentar e demonstrar uma automação confiável.","instructions":"Execute cinco cenários: sucesso, entrada inválida, baixa confiança, evento duplicado e falha externa. Para cada um, confira estado, saída e log. Corrija a falha de maior risco, finalize diagrama e documentação de operação, monte painel ou relatório simples e demonstre o processo antes e depois.","continuity_guidance":"A automação entra no portfólio como prova de modelagem de processo, integração e confiabilidade.","context":"Project Day mede se o fluxo continua explicável quando algo sai do caminho feliz.","expected_result":"Workflow final, cinco testes registrados, documentação, visão de acompanhamento e demonstração.","steps":["Congele o escopo e prepare massa de teste","Execute os cinco cenários obrigatórios","Inspecione estados, saídas e logs","Corrija o risco prioritário","Documente, exporte e apresente o fluxo"],"plan_b":"Sem integrações externas, demonstre com fixtures e saídas de teste, mantendo regras, estados e logs reais.","reflection_prompt":"Qual falha seria mais perigosa em uso real e como seu fluxo a contém?","portfolio_evidence":"Export final, diagrama, relatório ou painel, matriz de testes e vídeo ou demo.","tool_hint":"n8n, navegador, ferramenta de diagrama e documento operacional."},
    {"n":13,"title":"Product brief e protótipo do fluxo principal","objective":"Escolher um problema e recortar um MVP novo que integre IA, experiência e automação.","instructions":"Converse com um usuário possível ou registre evidência observável do problema. Defina usuário, situação, dor, promessa, hipótese e uma métrica simples. Desenhe um fluxo principal completo e marque onde IA, interface e automação geram valor. Corte funcionalidades até caber nas quatro aulas e crie protótipo testável.","continuity_guidance":"Na próxima aula, o protótipo será transformado em interface responsiva, dados e estados reais.","context":"Uma plataforma para organizar evento escolar é o exemplo; o aluno pode escolher qualquer produto novo com o mesmo contrato de integração.","expected_result":"Product brief, evidência do problema, métrica, mapa do fluxo, recorte de escopo e protótipo.","steps":["Colete evidência do problema e defina usuário","Escreva promessa, hipótese e métrica","Mapeie o fluxo principal e as três competências","Separe agora, depois e fora de escopo","Prototipe e faça uma primeira leitura com alguém"],"plan_b":"Sem entrevistado disponível, use observação documentada e teste o protótipo com colega ou professor, declarando a limitação.","reflection_prompt":"Que corte tornou seu MVP menor sem destruir a promessa central?","portfolio_evidence":"Product brief, evidência, mapa de fluxo, priorização e protótipo.","tool_hint":"Documento, quadro de priorização e ferramenta de prototipação."},
    {"n":14,"title":"Interface, dados e estados do MVP","objective":"Construir a experiência responsiva e a base de dados mínima do fluxo principal.","instructions":"Defina identidade e componentes a partir da promessa do produto. Implemente o fluxo principal em 375, 768 e 1440 px com estados vazio, carregando, sucesso e erro. Modele e persista somente os dados necessários, valide entradas e mostre ao usuário o que aconteceu e o próximo passo.","continuity_guidance":"Na próxima aula, IA e automação serão ligadas a essa experiência e aos dados validados.","context":"A interface precisa funcionar com dados reais e falhas previstas antes de receber complexidade de IA.","expected_result":"Frontend responsivo, estados essenciais, esquema mínimo e persistência do fluxo.","steps":["Defina sistema visual e componentes essenciais","Modele dados e regras de validação","Implemente o caminho principal responsivo","Adicione os quatro estados obrigatórios","Persista e recupere uma execução real"],"plan_b":"Sem banco, use armazenamento local com esquema documentado e mantenha a mesma validação e estados.","reflection_prompt":"Que dado você decidiu não guardar e por quê?","portfolio_evidence":"Interface, esquema de dados, validações e evidências responsivas dos estados.","tool_hint":"Next.js, Supabase ou armazenamento local, Zod e navegador responsivo."},
    {"n":15,"title":"Integração inteligente e confiável","objective":"Ligar IA, dados e automação ao produto com segurança, fallback e observabilidade.","instructions":"Implemente a rota de IA com prompt e saída estruturada, modelo de fallback e rate limit. Use o resultado validado para acionar a automação e atualizar o estado do produto. Proteja segredos, trate duplicidade e falha, registre eventos úteis e permita recuperação. Execute o fluxo inteiro com dados de teste.","continuity_guidance":"No Demo Day, o produto será testado com outra pessoa, corrigido, documentado e publicado.","context":"O valor está no fluxo integrado: entrada, inteligência, decisão, consequência e retorno visível ao usuário.","expected_result":"Fluxo ponta a ponta com IA, automação, estado, segurança e recuperação funcionando em conjunto.","steps":["Implemente IA com esquema, fallback e limites","Conecte saída validada à automação","Atualize estado e feedback na interface","Adicione idempotência, logs e recuperação","Teste integração completa e registre falhas"],"plan_b":"Use fixtures de IA e adaptadores simulados para provar o contrato e o fluxo quando um serviço externo estiver indisponível.","reflection_prompt":"Onde uma saída inválida poderia causar efeito real e qual barreira impede isso?","portfolio_evidence":"Integração funcional, arquitetura, prompt, workflow e registros de sucesso e recuperação.","tool_hint":"Groq, Next.js, Supabase, n8n ou rota server-side equivalente."},
    {"n":16,"title":"Demo Day: meu Produto Inteligente","objective":"Provar valor, confiabilidade e autoria em um MVP publicado e demonstrado ponta a ponta.","instructions":"Execute cinco cenários, incluindo sucesso, entrada inválida, falha da IA, repetição e recuperação. Teste com outra pessoa e implemente ao menos uma melhoria observada. Revise privacidade, segredos, acessibilidade e responsividade. Finalize README, diagrama, limites e próximos passos, publique e apresente problema, fluxo, decisões e evidências.","continuity_guidance":"O MVP encerra o Explorer e organiza as competências dos quatro projetos no portfólio do aluno.","context":"Demo Day demonstra um fluxo central confiável; quantidade de telas e funcionalidades secundárias não define qualidade.","expected_result":"MVP público, repositório, documentação, cinco testes, melhoria externa e apresentação final.","steps":["Congele o escopo e execute cinco cenários","Observe outra pessoa usando o fluxo","Implemente uma melhoria baseada no teste","Revise segurança, acessibilidade e responsividade","Documente, publique e apresente o MVP"],"plan_b":"Sem deploy, entregue execução local gravada, repositório reproduzível, evidências dos testes e plano exato de publicação.","reflection_prompt":"Que evidência mostra que seu produto entrega valor e qual hipótese ainda precisa ser validada?","portfolio_evidence":"Deploy, repositório, README, arquitetura, matriz de testes, melhoria e apresentação final.","tool_hint":"GitHub, Vercel, Supabase, navegador e roteiro de Demo Day."}
  ]$activities$::jsonb) as x(
    n smallint,
    title text,
    objective text,
    instructions text,
    continuity_guidance text,
    context text,
    expected_result text,
    steps jsonb,
    plan_b text,
    reflection_prompt text,
    portfolio_evidence text,
    tool_hint text
  )
)
update logos_academy.activity_templates a set
  title = d.title,
  objective = d.objective,
  instructions = d.instructions,
  continuity_guidance = d.continuity_guidance,
  estimated_minutes = 45,
  context = d.context,
  expected_result = d.expected_result,
  steps = d.steps,
  plan_b = d.plan_b,
  reflection_prompt = d.reflection_prompt,
  portfolio_evidence = d.portfolio_evidence,
  tool_hint = d.tool_hint,
  updated_at = now()
from data d
where a.id = md5('logos-academy-explorer-v3-activity-' || d.n)::uuid;

update logos_academy.activity_requirements
set deleted_at = now(), updated_at = now()
where activity_template_id in (
  select md5('logos-academy-explorer-v3-activity-' || n)::uuid
  from generate_series(1, 16) n
);

with tenant as (
  select id from logos_academy.tenants where slug = 'logos-academy' and deleted_at is null
), data(activity, position, kind, required, label, slot) as (values
  (1,1,'text',true,'Brief, público e problema do assistente',null),(1,2,'text',true,'Contrato com três modos e limites','prompt'),(1,3,'file',true,'Interface-base responsiva','frontend'),(1,4,'github_repository',true,'Repositório inicial','repository'),
  (2,1,'file',true,'Rota server-side validada','api'),(2,2,'text',true,'System prompt e instruções dos três modos','prompt'),(2,3,'text',true,'Esquema estruturado de entrada e saída',null),(2,4,'text',true,'Evidência de segredo protegido e testes',null),
  (3,1,'file',true,'Histórico e janela de contexto','frontend'),(3,2,'file',true,'Fallback, rate limit e recuperação','api'),(3,3,'file',true,'Renderizador visual seguro','frontend'),(3,4,'text',true,'Registro de falhas e retomadas','tests'),
  (4,1,'external_link',true,'Assistente publicado','deploy'),(4,2,'github_repository',true,'Repositório final','repository'),(4,3,'text',true,'Matriz com cinco testes e correção','tests'),(4,4,'file',true,'README com arquitetura, limites e privacidade',null),(4,5,'file',false,'Vídeo ou backup visual da demonstração',null),
  (5,1,'text',true,'Brief completo da campanha','prompt'),(5,2,'file',true,'Painel de referências comentadas',null),(5,3,'file',true,'Três direções criativas',null),(5,4,'text',true,'Matriz de decisão e direção escolhida','tests'),
  (6,1,'file',true,'Guia do sistema visual','frontend'),(6,2,'text',true,'Prompts e critérios de curadoria','prompt'),(6,3,'file',true,'Três peças em formatos diferentes','frontend'),(6,4,'text',true,'Copies adaptadas aos canais',null),
  (7,1,'github_repository',true,'Repositório da landing','repository'),(7,2,'file',true,'Landing responsiva com movimento','frontend'),(7,3,'file',true,'Vídeo curto ou storyboard completo',null),(7,4,'text',true,'Checklist de acessibilidade e reduced motion','tests'),
  (8,1,'external_link',true,'Campanha e landing publicadas','deploy'),(8,2,'github_repository',true,'Repositório final','repository'),(8,3,'file',true,'Case do Creative Studio',null),(8,4,'text',true,'Revisão externa e melhoria aplicada','tests'),
  (9,1,'file',true,'Diagrama do processo atual e futuro',null),(9,2,'text',true,'Contrato de entrada, estados e validações','api'),(9,3,'text',true,'Catálogo de exceções e revisão humana',null),(9,4,'text',true,'Critério de sucesso mensurável','tests'),
  (10,1,'file',true,'Export do workflow executável','api'),(10,2,'file',true,'Esquema e amostra de dados persistidos',null),(10,3,'text',true,'Regras determinísticas documentadas','prompt'),(10,4,'file',true,'Evidência da saída útil',null),
  (11,1,'text',true,'Prompt e esquema da etapa de IA','prompt'),(11,2,'file',true,'Workflow com revisão, idempotência e retry','api'),(11,3,'text',true,'Política de logs e dados sensíveis',null),(11,4,'text',true,'Testes de incerteza, duplicidade e falha','tests'),
  (12,1,'file',true,'Export final e diagrama operacional','api'),(12,2,'text',true,'Matriz dos cinco cenários','tests'),(12,3,'file',true,'Painel ou relatório de acompanhamento','frontend'),(12,4,'github_repository',true,'Repositório ou pacote reproduzível','repository'),(12,5,'external_link',false,'Demonstração publicada','deploy'),
  (13,1,'text',true,'Product brief, hipótese e métrica','prompt'),(13,2,'file',true,'Evidência do problema e recorte de escopo',null),(13,3,'file',true,'Mapa do fluxo integrado',null),(13,4,'file',true,'Protótipo testável','frontend'),(13,5,'github_repository',true,'Repositório inicial','repository'),
  (14,1,'file',true,'Interface responsiva do fluxo principal','frontend'),(14,2,'file',true,'Esquema de dados e validações','api'),(14,3,'text',true,'Evidência dos quatro estados essenciais','tests'),(14,4,'file',true,'Persistência e recuperação de uma execução',null),
  (15,1,'file',true,'Rota de IA com fallback e limites','api'),(15,2,'text',true,'Prompt e saída estruturada','prompt'),(15,3,'file',true,'Automação integrada ao estado do produto',null),(15,4,'text',true,'Logs, idempotência e recuperação','tests'),
  (16,1,'external_link',true,'MVP publicado','deploy'),(16,2,'github_repository',true,'Repositório final','repository'),(16,3,'text',true,'Cinco testes ponta a ponta','tests'),(16,4,'text',true,'Teste externo e melhoria aplicada',null),(16,5,'file',true,'README e diagrama de arquitetura',null),(16,6,'file',true,'Apresentação final do Demo Day',null)
)
insert into logos_academy.activity_requirements(
  id, tenant_id, activity_template_id, kind, label, is_required, position, project_slot, deleted_at, updated_at
)
select
  md5('logos-academy-explorer-v3-requirement-' || d.activity || '-' || d.position)::uuid,
  t.id,
  md5('logos-academy-explorer-v3-activity-' || d.activity)::uuid,
  d.kind,
  d.label,
  d.required,
  d.position,
  d.slot,
  null,
  now()
from tenant t cross join data d
on conflict (id) do update set
  kind = excluded.kind,
  label = excluded.label,
  is_required = excluded.is_required,
  position = excluded.position,
  project_slot = excluded.project_slot,
  deleted_at = null,
  updated_at = now();

update logos_academy.activity_criteria
set deleted_at = now(), updated_at = now()
where activity_template_id in (
  select md5('logos-academy-explorer-v3-activity-' || n)::uuid
  from generate_series(1, 16) n
);

with tenant as (
  select id from logos_academy.tenants where slug = 'logos-academy' and deleted_at is null
), data(activity, position, label, description) as (values
  (1,1,'Problema específico','Público, necessidade e promessa são concretos e diferentes de um chat genérico.'),(1,2,'Contrato completo','Há três modos ou especialidades, instrução complementar e limites explícitos.'),(1,3,'Interface utilizável','O fluxo é responsivo e comunica estados vazio e carregando.'),(1,4,'Autoria explicada','As escolhas visuais e de interação são justificadas; elemento reativo é opcional.'),
  (2,1,'Segredo protegido','A chave não aparece em cliente, arquivo enviado, repositório ou log.'),(2,2,'Entrada validada','A rota rejeita entrada ausente, excessiva ou em formato incorreto.'),(2,3,'Modos realmente distintos','Cada seleção altera instrução e comportamento sem quebrar regras permanentes.'),(2,4,'Saída previsível','O contrato estruturado é validável e renderizável pela interface.'),
  (3,1,'Contexto controlado','O histórico é persistido sem enviar conversa ilimitada ao modelo.'),(3,2,'Falha recuperável','Fallback, erro e nova tentativa possuem comportamento verificável.'),(3,3,'Uso limitado','Rate limit ocorre no servidor e informa o usuário com clareza.'),(3,4,'Visual seguro','A aplicação renderiza uma estrutura validada e não injeta SVG arbitrário.'),
  (4,1,'Fluxo completo','Interface, modos, IA, memória e proteções funcionam no deploy.'),(4,2,'Cinco testes relevantes','A matriz cobre sucesso, regra proibida, modo, fallback e limite ou contexto.'),(4,3,'Melhoria comprovada','Ao menos uma falha encontrada foi corrigida e comparada.'),(4,4,'Projeto explicável','README, arquitetura, limites e demonstração permitem compreender a solução.'),
  (5,1,'Brief acionável','Objetivo, público, mensagem, tom, canais, restrições e CTA orientam a criação.'),(5,2,'Direções distintas','As três opções diferem em conceito, composição e linguagem, não apenas em cor.'),(5,3,'Referências analisadas','Cada referência registra o princípio aproveitado sem propor cópia.'),(5,4,'Escolha justificada','A matriz compara critérios e explica a direção selecionada.'),
  (6,1,'Sistema consistente','Tokens e componentes sustentam reconhecimento entre as peças.'),(6,2,'Curadoria documentada','Prompts, descartes e motivo das escolhas estão registrados.'),(6,3,'Adaptação real','Os formatos mudam hierarquia e composição conforme o canal.'),(6,4,'Copy coerente','Texto, tom e chamada para ação seguem brief e espaço disponível.'),
  (7,1,'Narrativa clara','Landing e vídeo conduzem da promessa ao CTA sem contradição.'),(7,2,'Responsividade','O fluxo principal funciona em 375, 768 e 1440 px.'),(7,3,'Movimento com função','Animação orienta atenção e respeita preferência por redução.'),(7,4,'Audiovisual completo','Vídeo ou storyboard define gancho, cenas, ritmo, texto ou áudio e encerramento.'),
  (8,1,'Coerência do sistema','Brief, identidade, peças, página e audiovisual comunicam a mesma ideia.'),(8,2,'Revisão externa','Outra pessoa descreveu a mensagem e sua leitura foi registrada.'),(8,3,'Correção priorizada','A incoerência de maior impacto foi corrigida antes da publicação.'),(8,4,'Case explicável','A entrega mostra processo, decisões, descartes, resultado e próximos passos.'),
  (9,1,'Problema observável','O processo atual apresenta frequência, esforço, erro ou risco identificável.'),(9,2,'Fluxos compreensíveis','Diagramas mostram atores, entrada, decisões, saídas e exceções.'),(9,3,'Contrato validável','Campos, tipos, obrigatoriedade, estados e consentimento estão definidos.'),(9,4,'Limite humano','Casos que exigem revisão estão separados das decisões automáticas.'),
  (10,1,'Entrada confiável','Dados inválidos são recusados ou encaminhados antes do processamento.'),(10,2,'Estado persistido','Cada execução mantém identificador e estado rastreável.'),(10,3,'Regra explícita','Decisões previsíveis usam regra determinística compreensível.'),(10,4,'Saída útil','O caminho feliz gera consequência real e verificável.'),
  (11,1,'IA delimitada','A tarefa possui prompt, esquema, validação e confiança ou justificativa.'),(11,2,'Revisão segura','Baixa confiança e casos sensíveis não avançam automaticamente.'),(11,3,'Sem duplicidade','Repetir o mesmo evento não produz uma segunda consequência.'),(11,4,'Falha observável','Retry é limitado e logs explicam o estado sem expor informação sensível.'),
  (12,1,'Cenários completos','Sucesso, inválido, incerteza, duplicidade e falha externa foram executados.'),(12,2,'Estados coerentes','Cada cenário termina em estado, saída e log compatíveis.'),(12,3,'Risco corrigido','A falha de maior impacto recebeu correção demonstrável.'),(12,4,'Operação explicável','Diagrama, export e painel ou relatório permitem acompanhar o fluxo.'),
  (13,1,'Problema sustentado','Há evidência ou observação concreta de uma necessidade de usuário.'),(13,2,'Hipótese mensurável','Promessa, hipótese e métrica permitem avaliar valor.'),(13,3,'Escopo disciplinado','Agora, depois e fora de escopo mantêm um fluxo principal completo.'),(13,4,'Integração necessária','IA, experiência visual e automação têm papéis claros no mesmo fluxo.'),
  (14,1,'Valor visível','A interface destaca a tarefa e o resultado, não a tecnologia.'),(14,2,'Base responsiva','O fluxo funciona em 375, 768 e 1440 px.'),(14,3,'Estados completos','Vazio, carregando, sucesso e erro informam ação ou próximo passo.'),(14,4,'Dados mínimos','Modelo, validação, persistência e recuperação sustentam apenas o escopo aprovado.'),
  (15,1,'Fronteiras validadas','Entrada e saída são verificadas antes de IA, dados e efeitos externos.'),(15,2,'Fallback funcional','Falha do modelo principal não encerra o fluxo silenciosamente.'),(15,3,'Automação idempotente','A consequência usa estado ou chave que impede repetição indevida.'),(15,4,'Recuperação observável','Logs e feedback permitem diagnosticar e retomar o fluxo.'),
  (16,1,'Valor ponta a ponta','O deploy entrega a promessa central em um fluxo completo.'),(16,2,'Cinco cenários','A matriz cobre sucesso, inválido, falha da IA, repetição e recuperação.'),(16,3,'Aprendizado externo','O teste com outra pessoa resultou em melhoria identificável.'),(16,4,'Defesa autoral','O aluno explica problema, arquitetura, decisões, limites, evidências e próximos passos.')
)
insert into logos_academy.activity_criteria(
  id, tenant_id, activity_template_id, label, description, position, deleted_at, updated_at
)
select
  md5('logos-academy-explorer-v3-criterion-' || d.activity || '-' || d.position)::uuid,
  t.id,
  md5('logos-academy-explorer-v3-activity-' || d.activity)::uuid,
  d.label,
  d.description,
  d.position,
  null,
  now()
from tenant t cross join data d
on conflict (id) do update set
  label = excluded.label,
  description = excluded.description,
  position = excluded.position,
  deleted_at = null,
  updated_at = now();

commit;
